CREATE TABLE IF NOT EXISTS "vehicles" (
	"vin" varchar(17) PRIMARY KEY NOT NULL,
	"primary_driver_no" text,
	"accounting_account" text,
	"model" text,
	"model_name" text,
	"model_type" text,
	"trim_level" text,
	"engine_description" text,
	"engine_no" text,
	"color" text,
	"interior_color" text,
	"body_style" text,
	"fuel_type" text,
	"year" integer,
	"make" text,
	"make_name" text,
	"manufacturer" text,
	"plant_of_manufacture" text,
	"number_of_doors" integer,
	"cylinder_no" integer,
	"commission_price" numeric(10, 2),
	"retail_price_update_date" date,
	"vehicle_sold_date" date,
	"sold_date" date,
	"mileage" integer,
	"sold_mileage" integer,
	"stock_no" text,
	"stock_type" text,
	"status" text,
	"balance" numeric(10, 2),
	"price1" numeric(10, 2),
	"price2" numeric(10, 2),
	"options" jsonb,
	"order_date" date,
	"expected_delivery_date" date,
	"actual_cash_value" numeric(10, 2),
	"advertised_price" numeric(10, 2),
	"advertised_price_exp_date" date,
	"advertised_price_start_date" date,
	"total_options_cost" numeric(10, 2),
	"total_options_invoice" numeric(10, 2),
	"total_options_retail" numeric(10, 2),
	"invoice_pack_amount" numeric(10, 2),
	"commission_pack_amount" numeric(10, 2),
	"commission_pack_percent" numeric(10, 2),
	"entry_date" date,
	"last_activity_date" date
);
