ALTER TABLE "vehicles" RENAME COLUMN "vin" TO "VIN";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "primary_driver_no" TO "PrimaryDriverNo";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "accounting_account" TO "AccountingAccount";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "model" TO "Model";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "model_name" TO "ModelName";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "model_type" TO "ModelType";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "trim_level" TO "TrimLevel";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "engine_description" TO "EngineDescription";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "engine_no" TO "EngineNo";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "color" TO "Color";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "interior_color" TO "InteriorColor";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "body_style" TO "BodyStyle";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "fuel_type" TO "FuelType";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "year" TO "Year";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "make" TO "Make";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "make_name" TO "MakeName";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "manufacturer" TO "Manufacturer";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "plant_of_manufacture" TO "PlantOfManufacture";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "number_of_doors" TO "NumberOfDoors";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "cylinder_no" TO "CylinderNo";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "commission_price" TO "CommissionPrice";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "retail_price_update_date" TO "RetailPriceUpdateDate";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "vehicle_sold_date" TO "VehicleSoldDate";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "sold_date" TO "SoldDate";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "mileage" TO "Mileage";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "sold_mileage" TO "SoldMileage";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "stock_no" TO "StockNo";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "stock_type" TO "StockType";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "status" TO "Status";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "balance" TO "Balance";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "price1" TO "Price1";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "price2" TO "Price2";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "options" TO "Options";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "order_date" TO "OrderDate";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "expected_delivery_date" TO "ExpectedDeliveryDate";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "actual_cash_value" TO "ActualCashValue";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "advertised_price" TO "AdvertisedPrice";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "advertised_price_exp_date" TO "AdvertisedPriceExpDate";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "advertised_price_start_date" TO "AdvertisedPriceStartDate";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "total_options_cost" TO "TotalOptionsCost";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "total_options_invoice" TO "TotalOptionsInvoice";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "total_options_retail" TO "TotalOptionsRetail";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "invoice_pack_amount" TO "InvoicePackAmount";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "commission_pack_amount" TO "CommissionPackAmount";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "commission_pack_percent" TO "CommissionPackPercent";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "entry_date" TO "EntryDate";--> statement-breakpoint
ALTER TABLE "vehicles" RENAME COLUMN "last_activity_date" TO "LastActivityDate";