import {
  pgTable,
  varchar,
  primaryKey,
  numeric,
  integer,
  smallint,
  date,
  bigint,
  text,
} from "drizzle-orm/pg-core";

export const GLJE = pgTable(
  "GLJE",
  {
    hostItemId: text("HostItemID").notNull(),
    accountingDate: date("AccountingDate").notNull(),
    accountNumber: text("AccountNumber").notNull(),
    accountNumberRight: text("AccountNumberRight").notNull(),
    companyID: text("CompanyID").notNull(),
    companyIDRight: text("CompanyIDRight").notNull(),
    control: text("Control"),
    control2: text("Control2"),
    controlRight: text("ControlRight"),
    control2Right: text("Control2Right"),
    controlType: integer("ControlType"),
    controlType2: integer("ControlType2"),
    currentMonth: text("CurrentMonth"),
    detailDescription: text("DetailDescription"),
    distillControlType: integer("DistillControlType"),
    distillControlType2: integer("DistillControlType2"),
    errorLevel: integer("ErrorLevel"),
    errorMessage: text("ErrorMessage"),
    journalID: integer("JournalID"),
    journalIDRight: integer("JournalIDRight"),
    postingAmount: numeric("PostingAmount", { precision: 10, scale: 2 }),
    postingSequence: integer("PostingSequence"),
    postingTime: bigint("PostingTime", { mode: "number" }),
    prodNo: text("ProdNo"),
    prodNo2: text("ProdNo2"),
    prodNoRight: text("ProdNoRight"),
    prodNo2Right: text("ProdNo2Right"),
    prodType: integer("ProdType"),
    prodType2: integer("ProdType2"),
    refer: text("Refer"),
    referRight: text("ReferRight"),
    scheduleNumber: text("ScheduleNumber"),
    statCount: integer("StatCount"),
  },
  (table) => {
    return {
      accountingRecordsPkey: primaryKey({
        columns: [table.hostItemId, table.accountingDate, table.accountNumber],
        name: "GLJE_pkey",
      }),
    };
  },
);

export const COA = pgTable(
  "COA",
  {
    statCountType: text("StatCountType"),
    pattern: text("Pattern"),
    postDescFlag: text("PostDescFlag"),
    techFlag: text("TechFlag"),
    hostItemId: text("HostItemID").notNull(),
    accountDescription: text("AccountDescription"),
    accountNumber: text("AccountNumber").notNull(),
    accountNumberRight: text("AccountNumberRight").notNull(),
    accountType: text("AccountType"),
    acctSubType: text("AcctSubType"),
    acctUpdDate: date("AcctUpdDate"),
    beginDate: date("BeginDate"),
    cntl2Type: text("Cntl2Type"),
    cntlType: text("CntlType"),
    companyID: text("CompanyID").notNull(),
    companyIDRight: text("CompanyIDRight").notNull(),
    deptID: text("DeptID"),
    deptIDRight: text("DeptIDRight"),
    endDate: date("EndDate"),
    errorLevel: integer("ErrorLevel"),
    errorMessage: text("ErrorMessage"),
    franchiseId: text("FranchiseId"),
    bfSched: text("BFSched"),
    dfSched: text("DFSched"),
    incBalGrp: text("IncBalGrp"),
    incBalGrpDesc: text("IncBalGrpDesc"),
    incBalSubGrp: text("IncBalSubGrp"),
    incBalSubGrpDesc: text("IncBalSubGrpDesc"),
    prodType: integer("ProdType"),
    rptGrp: text("RptGrp"),
    rptGrpDesc: text("RptGrpDesc"),
    unaGrp: text("UnaGrp"),
    unaGrpDesc: text("UnaGrpDesc"),
    chain: text("Chain"),
  },
  (table) => {
    return {
      financialRecordsPkey: primaryKey({
        columns: [table.hostItemId, table.accountNumber, table.companyID],
        name: "COA_pkey",
      }),
    };
  },
);

export const dealInitialfee = pgTable(
  "deal_initialfee",
  {
    fiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    branch: varchar("Branch", { length: 20 }).notNull(),
    hostItemId: varchar("HostItemID", { length: 20 }).notNull(),
    initialFee4ProfitType: varchar("InitialFee4ProfitType", { length: 1 }),
  },
  (table) => {
    return {
      dealInitialfeePkey: primaryKey({
        columns: [table.fiWipStatusCode, table.branch, table.hostItemId],
        name: "deal_initialfee_pkey",
      }),
    };
  },
);

export const dealTradedealerdefined = pgTable(
  "deal_tradedealerdefined",
  {
    fiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    branch: varchar("Branch", { length: 20 }).notNull(),
    hostItemId: varchar("HostItemID", { length: 20 }).notNull(),
    tradeDealerDefined1: varchar("TradeDealerDefined1", { length: 17 }),
    tradeDealerDefined2: varchar("TradeDealerDefined2", { length: 17 }),
    tradeDealerDefined3: varchar("TradeDealerDefined3", { length: 17 }),
    tradeDealerDefined4: varchar("TradeDealerDefined4", { length: 17 }),
    tradeDealerDefined5: varchar("TradeDealerDefined5", { length: 17 }),
    tradeDealerDefined6: varchar("TradeDealerDefined6", { length: 17 }),
    tradeDealerDefined7: varchar("TradeDealerDefined7", { length: 17 }),
    tradeDealerDefined8: varchar("TradeDealerDefined8", { length: 17 }),
  },
  (table) => {
    return {
      dealTradedealerdefinedPkey: primaryKey({
        columns: [table.fiWipStatusCode, table.branch, table.hostItemId],
        name: "deal_tradedealerdefined_pkey",
      }),
    };
  },
);

export const dealTrade2 = pgTable(
  "deal_trade2",
  {
    fiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    branch: varchar("Branch", { length: 20 }).notNull(),
    hostItemId: varchar("HostItemID", { length: 20 }).notNull(),
    trade2Acv: varchar("Trade2ACV", { length: 17 }),
    trade2Color: varchar("Trade2Color", { length: 17 }),
    trade2Gross: numeric("Trade2Gross", { precision: 10, scale: 2 }),
    trade2Make: varchar("Trade2Make", { length: 50 }),
    trade2Mileage: integer("Trade2Mileage"),
    trade2Model: varchar("Trade2Model", { length: 17 }),
    trade2ModelName: varchar("Trade2ModelName", { length: 17 }),
    trade2ModelNo: varchar("Trade2ModelNo", { length: 17 }),
    trade2ModelType: varchar("Trade2ModelType", { length: 17 }),
    trade2Over: numeric("Trade2Over", { precision: 10, scale: 2 }),
    trade2PayOff: numeric("Trade2PayOff", { precision: 10, scale: 2 }),
    trade2Stock: varchar("Trade2Stock", { length: 50 }),
    trade2Style: varchar("Trade2Style", { length: 15 }),
    trade2Vin: varchar("Trade2VIN", { length: 17 }),
    trade2Year: integer("Trade2Year"),
  },
  (table) => {
    return {
      dealTrade2Pkey: primaryKey({
        columns: [table.fiWipStatusCode, table.branch, table.hostItemId],
        name: "deal_trade2_pkey",
      }),
    };
  },
);

export const dealTrade1 = pgTable(
  "deal_trade1",
  {
    fiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    branch: varchar("Branch", { length: 20 }).notNull(),
    hostItemId: varchar("HostItemID", { length: 20 }).notNull(),
    trade1Model: varchar("Trade1Model", { length: 50 }),
    trade1ModelName: varchar("Trade1ModelName", { length: 50 }),
    trade1ModelNo: varchar("Trade1ModelNo", { length: 50 }),
    trade1ModelType: varchar("Trade1ModelType", { length: 50 }),
    trade1Over: numeric("Trade1Over", { precision: 10, scale: 2 }),
    trade1PayOff: numeric("Trade1PayOff", { precision: 10, scale: 2 }),
    trade1Stock: varchar("Trade1Stock", { length: 50 }),
    trade1Style: varchar("Trade1Style", { length: 15 }),
    trade1Vin: varchar("Trade1VIN", { length: 17 }),
    trade1Year: integer("Trade1Year"),
    trade1Acv: numeric("Trade1ACV", { precision: 12, scale: 2 }),
    trade1Color: varchar("Trade1Color", { length: 50 }),
    trade1Gross: numeric("Trade1Gross", { precision: 12, scale: 2 }),
    trade1Make: varchar("Trade1Make", { length: 50 }),
    trade1MakeName: varchar("Trade1MakeName", { length: 50 }),
    trade1Mileage: integer("Trade1Mileage"),
  },
  (table) => {
    return {
      dealTrade1Pkey: primaryKey({
        columns: [table.fiWipStatusCode, table.branch, table.hostItemId],
        name: "deal_trade1_pkey",
      }),
    };
  },
);

export const dealFiaux = pgTable(
  "deal_fiaux",
  {
    fiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    branch: varchar("Branch", { length: 20 }).notNull(),
    hostItemId: varchar("HostItemID", { length: 20 }).notNull(),
    fiAux1: varchar("FiAux1", { length: 50 }),
    fiAux40: integer("FiAux40"),
    fiAux41: integer("FiAux41"),
    fiAux42: integer("FiAux42"),
    fiAux43: integer("FiAux43"),
    fiAux44: integer("FiAux44"),
    fiAux45: integer("FiAux45"),
    fiAux46: integer("FiAux46"),
    fiAux47: integer("FiAux47"),
    fiAux48: integer("FiAux48"),
    fiAux49: integer("FiAux49"),
    fiAux5: integer("FiAux5"),
    fiAux50: varchar("FiAux50", { length: 50 }),
    fiAux6: varchar("FiAux6", { length: 50 }),
    fiAux7: integer("FiAux7"),
    fiAux8: varchar("FiAux8", { length: 50 }),
    fiAux9: varchar("FiAux9", { length: 50 }),
    fiAux10: varchar("FiAux10", { length: 50 }),
    fiAux11: varchar("FiAux11", { length: 50 }),
    fiAux12: varchar("FiAux12", { length: 50 }),
    fiAux13: varchar("FiAux13", { length: 50 }),
    fiAux14: varchar("FiAux14", { length: 50 }),
  },
  (table) => {
    return {
      dealFiauxPkey: primaryKey({
        columns: [table.fiWipStatusCode, table.branch, table.hostItemId],
        name: "deal_fiaux_pkey",
      }),
    };
  },
);

export const customers = pgTable(
  "customers",
  {
    hostItemId: varchar("HostItemID", { length: 40 }).notNull(),
    custNo: varchar("CustNo", { length: 17 }).notNull(),
    errorLevel: varchar("ErrorLevel", { length: 1 }).notNull(),
    nameCode: varchar("NameCode", { length: 1 }).notNull(),
    dateAdded: date("DateAdded").notNull(),
    blockEmail: varchar("BlockEMail", { length: 1 }).notNull(),
    blockMail: varchar("BlockMail", { length: 1 }).notNull(),
    blockPhone: varchar("BlockPhone", { length: 1 }).notNull(),
    mailability: varchar("Mailability", { length: 1 }),
    nameBalances1: numeric("NameBalances1", { precision: 15, scale: 2 }),
    address: varchar("Address", { length: 45 }),
    addressSecondLine: varchar("AddressSecondLine", { length: 45 }),
    businessPhone: varchar("BusinessPhone", { length: 20 }),
    businessPhoneExt: varchar("BusinessPhoneExt", { length: 7 }),
    cellular: varchar("Cellular", { length: 20 }),
    city: varchar("City", { length: 35 }),
    contactMethod: varchar("ContactMethod", { length: 1 }),
    country: varchar("Country", { length: 20 }),
    county: varchar("County", { length: 25 }),
    driverLicenseStOrProv: varchar("DriverLicenseStOrProv", { length: 2 }),
    email: varchar("Email", { length: 50 }),
    emailDesc: varchar("EmailDesc", { length: 20 }),
    emailDesc2: varchar("EmailDesc2", { length: 20 }),
    emailDesc3: varchar("EmailDesc3", { length: 20 }),
    employer: varchar("Employer", { length: 32 }),
    errorMessage: varchar("ErrorMessage", { length: 80 }),
    firstName: varchar("FirstName", { length: 25 }),
    homeFax: varchar("HomeFax", { length: 20 }),
    telephone: varchar("Telephone", { length: 12 }),
    language: varchar("Language", { length: 2 }),
    lastName: varchar("LastName", { length: 40 }),
    middleName: varchar("MiddleName", { length: 25 }),
    name1: varchar("Name1", { length: 45 }),
    name2Company: varchar("Name2Company", { length: 30 }),
    nameCompany: varchar("NameCompany", { length: 45 }),
    pager: varchar("Pager", { length: 20 }),
    partsCounterCode: varchar("PartsCounterCode", { length: 20 }),
    partsFlag: varchar("PartsFlag", { length: 2 }),
    partsType: varchar("PartsType", { length: 1 }),
    preferredContactDay: varchar("PreferredContactDay", { length: 1 }),
    preferredContactMethod: varchar("PreferredContactMethod", { length: 1 }),
    preferredContactTime: varchar("PreferredContactTime", { length: 1 }),
    saleType: varchar("SaleType", { length: 20 }),
    secondaryHomePhone: varchar("SecondaryHomePhone", { length: 12 }),
    state: varchar("State", { length: 2 }),
    taxCode: varchar("TaxCode", { length: 20 }),
    title1: varchar("Title1", { length: 30 }),
    zipOrPostalCode: varchar("ZipOrPostalCode", { length: 20 }),
    homePhone: varchar("HomePhone", { length: 12 }),
    preferredLanguage: varchar("PreferredLanguage", { length: 20 }),
    comment: varchar("Comment", { length: 255 }),
    commentDate: date("CommentDate"),
    driverLicenseExpDate: date("DriverLicenseExpDate"),
    email2: varchar("Email2", { length: 50 }),
    email3: varchar("Email3", { length: 50 }),
    lastUpdated: date("LastUpdated"),
    gender: varchar("Gender", { length: 1 }),
    creditLimit: numeric("CreditLimit", { precision: 15, scale: 2 }),
    currentDue: numeric("CurrentDue", { precision: 12, scale: 2 }),
    over30Due: numeric("Over30Due", { precision: 12, scale: 2 }),
    over60Due: numeric("Over60Due", { precision: 12, scale: 2 }),
    over90Due: numeric("Over90Due", { precision: 12, scale: 2 }),
    over120Due: numeric("Over120Due", { precision: 12, scale: 2 }),
    specInstructions2: varchar("SpecInstructions2", { length: 60 }),
    specInstructions3: varchar("SpecInstructions3", { length: 60 }),
    specInstructions4: varchar("SpecInstructions4", { length: 60 }),
    specInstructions5: varchar("SpecInstructions5", { length: 60 }),
    insAgency: varchar("InsAgency", { length: 30 }),
    insAgentAddress1: varchar("InsAgentAddress1", { length: 45 }),
    insAgentAddress2: varchar("InsAgentAddress2", { length: 45 }),
    insAgentCity: varchar("InsAgentCity", { length: 35 }),
    insAgentPhone: varchar("InsAgentPhone", { length: 20 }),
    insAgentState: varchar("InsAgentState", { length: 2 }),
    insAgentZipOrPostalCode: varchar("InsAgentZipOrPostalCode", { length: 20 }),
    insCompanyAddress1: varchar("InsCompanyAddress1", { length: 45 }),
    insCompanyAddress2: varchar("InsCompanyAddress2", { length: 45 }),
    insCompanyCity: varchar("InsCompanyCity", { length: 35 }),
    insCompanyPhone: varchar("InsCompanyPhone", { length: 20 }),
    insCompanyState: varchar("InsCompanyState", { length: 2 }),
    insCompanyZipOrPostalCode: varchar("InsCompanyZipOrPostalCode", {
      length: 20,
    }),
    insPolicyExpDate: date("InsPolicyExpDate"),
    insVerifiedBy: varchar("InsVerifiedBy", { length: 30 }),
    insVerifiedDate: date("InsVerifiedDate"),
    insPolicyNo: varchar("InsPolicyNo", { length: 25 }),
    serviceCustomer: varchar("ServiceCustomer", { length: 2 }),
    textMessagePhone: varchar("TextMessagePhone", { length: 20 }),
    textMessageCarrier: varchar("TextMessageCarrier", { length: 25 }),
    name2First: varchar("Name2First", { length: 20 }),
    name2Last: varchar("Name2Last", { length: 30 }),
    name2Middle: varchar("Name2Middle", { length: 20 }),
    name2Suffix: varchar("Name2Suffix", { length: 5 }),
    name2Title: varchar("Name2Title", { length: 5 }),
    nameSuffix: varchar("NameSuffix", { length: 5 }),
    nameTitle: varchar("NameTitle", { length: 5 }),
    insAgent: varchar("InsAgent", { length: 30 }),
    insCompany: varchar("InsCompany", { length: 30 }),
    specInstructions: varchar("SpecInstructions", { length: 40 }),
    deleteDataFlag: smallint("DeleteDataFlag"),
    optOutFlag: smallint("OptOutFlag"),
    optOutDate: date("OptOutDate"),
    optOutTime: varchar("OptOutTime", { length: 20 }),
    deleteDataDate: date("DeleteDataDate"),
    deleteDataTime: varchar("DeleteDataTime", { length: 20 }),
  },
  (table) => {
    return {
      customersPkey: primaryKey({
        columns: [table.hostItemId, table.custNo],
        name: "customers_pkey",
      }),
    };
  },
);

export const deals = pgTable(
  "deals",
  {
    fiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    branch: varchar("Branch", { length: 20 }).notNull(),
    hostItemId: varchar("HostItemID", { length: 20 }).notNull(),
    state: varchar("State", { length: 2 }),
    make: varchar("Make", { length: 50 }),
    makeName: varchar("MakeName", { length: 50 }),
    mileageExpected: integer("MileageExpected"),
    mileagePenaltyRate: numeric("MileagePenaltyRate", {
      precision: 10,
      scale: 2,
    }),
    stockNo: varchar("StockNo", { length: 50 }).notNull(),
    tax: numeric("Tax", { precision: 10, scale: 2 }),
    tax1Name: varchar("Tax1Name", { length: 50 }),
    tax1Rate: numeric("Tax1Rate", { precision: 10, scale: 2 }),
    tax1Base: numeric("Tax1Base", { precision: 10, scale: 2 }),
    tax1Amount: numeric("Tax1Amount", { precision: 10, scale: 2 }),
    mbiTerm: smallint("MBITerm"),
    msrp: numeric("MSRP", { precision: 10, scale: 2 }),
    mbiPolicyNo: varchar("MbiPolicyNo", { length: 50 }),
    mileagePenaltyAmount: varchar("MileagePenaltyAmount", { length: 50 }),
    surplusCash: numeric("SurplusCash", { precision: 10, scale: 2 }),
    tax2Amount: numeric("Tax2Amount", { precision: 10, scale: 2 }),
    tax2Name: varchar("Tax2Name", { length: 50 }),
    tax2Rate: numeric("Tax2Rate", { precision: 10, scale: 2 }),
    tax3Amount: numeric("Tax3Amount", { precision: 10, scale: 2 }),
    tax3Name: varchar("Tax3Name", { length: 50 }),
    tax3Rate: numeric("Tax3Rate", { precision: 10, scale: 2 }),
    tax4Amount: numeric("Tax4Amount", { precision: 10, scale: 2 }),
    tax4Name: varchar("Tax4Name", { length: 50 }),
    tax4Rate: numeric("Tax4Rate", { precision: 10, scale: 2 }),
    usLuxuryExciseTaxAmount: numeric("USLuxuryExciseTaxAmount", {
      precision: 10,
      scale: 2,
    }),
    feeOption3Amount: numeric("FeeOption3Amount", { precision: 10, scale: 2 }),
    feeOption3Cost: numeric("FeeOption3Cost", { precision: 10, scale: 2 }),
    feeOption3Name: varchar("FeeOption3Name", { length: 25 }),
    feeOption3ProfitType: varchar("FeeOption3ProfitType", { length: 2 }),
    feeOption4Amount: numeric("FeeOption4Amount", { precision: 10, scale: 2 }),
    feeOption4Cost: numeric("FeeOption4Cost", { precision: 10, scale: 2 }),
    feeOption4Name: varchar("FeeOption4Name", { length: 25 }),
    feeOption4ProfitType: varchar("FeeOption4ProfitType", { length: 2 }),
    feeOption5Amount: numeric("FeeOption5Amount", { precision: 10, scale: 2 }),
    feeOption5Cost: numeric("FeeOption5Cost", { precision: 10, scale: 2 }),
    feeOption5Name: varchar("FeeOption5Name", { length: 25 }),
    feeOption5ProfitType: varchar("FeeOption5ProfitType", { length: 2 }),
    feeOption6Amount: numeric("FeeOption6Amount", { precision: 10, scale: 2 }),
    feeOption6Cost: numeric("FeeOption6Cost", { precision: 10, scale: 2 }),
    feeOption6Name: varchar("FeeOption6Name", { length: 25 }),
    feeOption6ProfitType: varchar("FeeOption6ProfitType", { length: 2 }),
    feeOption7Amount: numeric("FeeOption7Amount", { precision: 10, scale: 2 }),
    feeOption7Cost: numeric("FeeOption7Cost", { precision: 10, scale: 2 }),
    feeOption7Name: varchar("FeeOption7Name", { length: 25 }),
    feeOption7ProfitType: varchar("FeeOption7ProfitType", { length: 2 }),
    feeOption8Amount: numeric("FeeOption8Amount", { precision: 10, scale: 2 }),
    feeOption8Cost: numeric("FeeOption8Cost", { precision: 10, scale: 2 }),
    feeOption8Name: varchar("FeeOption8Name", { length: 25 }),
    feeOption8ProfitType: varchar("FeeOption8ProfitType", { length: 2 }),
    feeOption9Amount: numeric("FeeOption9Amount", { precision: 10, scale: 2 }),
    feeOption9Cost: numeric("FeeOption9Cost", { precision: 10, scale: 2 }),
    feeOption9Name: varchar("FeeOption9Name", { length: 18 }),
    feeOption9ProfitType: varchar("FeeOption9ProfitType", { length: 2 }),
    initialFee4ProfitType: varchar("InitialFee4ProfitType", { length: 1 }),
    initialFee5Amount: numeric("InitialFee5Amount", {
      precision: 10,
      scale: 2,
    }),
    initialFee5CostAmount: numeric("InitialFee5CostAmount", {
      precision: 10,
      scale: 2,
    }),
    initialFee5Name: varchar("InitialFee5Name", { length: 21 }),
    initialFee5ProfitType: varchar("InitialFee5ProfitType", { length: 1 }),
    initialFee6Amount: numeric("InitialFee6Amount", {
      precision: 10,
      scale: 2,
    }),
    initialFee6CostAmount: numeric("InitialFee6CostAmount", {
      precision: 10,
      scale: 2,
    }),
    initialFee6Name: varchar("InitialFee6Name", { length: 21 }),
    initialFee6ProfitType: varchar("InitialFee6ProfitType", { length: 1 }),
    initialFee7Amount: numeric("InitialFee7Amount", {
      precision: 10,
      scale: 2,
    }),
    initialFee7CostAmount: numeric("InitialFee7CostAmount", {
      precision: 10,
      scale: 2,
    }),
    initialFee7Name: varchar("InitialFee7Name", { length: 21 }),
    initialFee7ProfitType: varchar("InitialFee7ProfitType", { length: 1 }),
    initialFee8Amount: numeric("InitialFee8Amount", {
      precision: 10,
      scale: 2,
    }),
    initialFee8CostAmount: numeric("InitialFee8CostAmount", {
      precision: 10,
      scale: 2,
    }),
    initialFee8Name: varchar("InitialFee8Name", { length: 21 }),
    initialFee8ProfitType: varchar("InitialFee8ProfitType", { length: 1 }),
    initialFee9Amount: numeric("InitialFee9Amount", {
      precision: 10,
      scale: 2,
    }),
    initialFee9CostAmount: numeric("InitialFee9CostAmount", {
      precision: 10,
      scale: 2,
    }),
    initialFee9Name: varchar("InitialFee9Name", { length: 21 }),
    initialFee9ProfitType: varchar("InitialFee9ProfitType", { length: 1 }),
    ins1Cost: numeric("Ins1Cost", { precision: 10, scale: 2 }),
    ins1Fee: numeric("Ins1Fee", { precision: 10, scale: 2 }),
    ins1Income: numeric("Ins1Income", { precision: 10, scale: 2 }),
    ins2Cost: numeric("Ins2Cost", { precision: 10, scale: 2 }),
    ins2Fee: numeric("Ins2Fee", { precision: 10, scale: 2 }),
    ins2Income: numeric("Ins2Income", { precision: 10, scale: 2 }),
    ins3Cost: numeric("Ins3Cost", { precision: 10, scale: 2 }),
    ins3Fee: numeric("Ins3Fee", { precision: 10, scale: 2 }),
    ins3Income: numeric("Ins3Income", { precision: 10, scale: 2 }),
    insurance1Deductible: numeric("Insurance1Deductible", {
      precision: 10,
      scale: 2,
    }),
    insurance1Limit: numeric("Insurance1Limit", { precision: 10, scale: 2 }),
    insurance1LimitMiles: smallint("Insurance1LimitMiles"),
    insurance1Name: varchar("Insurance1Name", { length: 21 }),
    balloonRate: numeric("BalloonRate", { precision: 10, scale: 2 }),
    onePayAmount: numeric("OnePayAmount", { precision: 10, scale: 2 }),
    finInstituteCode: varchar("FinInstituteCode", { length: 12 }),
    financeAmt: numeric("FinanceAmt", { precision: 10, scale: 2 }),
    financeCharge: numeric("FinanceCharge", { precision: 10, scale: 2 }),
    financeSource: varchar("FinanceSource", { length: 50 }),
    firstPayDate: date("FirstPayDate"),
    backGross: numeric("BackGross", { precision: 10, scale: 2 }),
    backWeOwes: numeric("BackWeOwes", { precision: 10, scale: 2 }),
    balloonAmount: numeric("BalloonAmount", { precision: 10, scale: 2 }),
    bankFee: numeric("BankFee", { precision: 10, scale: 2 }),
    baseResidual: numeric("BaseResidual", { precision: 10, scale: 2 }),
    billingClerk: integer("BillingClerk"),
    bodyStyle: varchar("BodyStyle", { length: 50 }),
    bonusSp1: numeric("BonusSP1", { precision: 10, scale: 2 }),
    bonusSp2: numeric("BonusSP2", { precision: 10, scale: 2 }),
    bonusSp3: numeric("BonusSP3", { precision: 10, scale: 2 }),
    businessPhone: varchar("BusinessPhone", { length: 50 }),
    buyRateApr: numeric("BuyRateAPR", { precision: 10, scale: 2 }),
    buyRateAddOn: numeric("BuyRateAddOn", { precision: 10, scale: 2 }),
    buyRateLfm: numeric("BuyRateLFM", { precision: 10, scale: 2 }),
    buyRateLmf: numeric("BuyRateLMF", { precision: 10, scale: 2 }),
    clCost: numeric("CLCost", { precision: 10, scale: 2 }),
    clIncome: numeric("CLIncome", { precision: 10, scale: 2 }),
    clPremium: numeric("CLPremium", { precision: 10, scale: 2 }),
    crmClosingMgrId: varchar("CRMClosingMgrId", { length: 50 }),
    crmClosingMgrName: varchar("CRMClosingMgrName", { length: 50 }),
    crmCommisionClosingMgr: varchar("CRMCommisionClosingMgr", { length: 50 }),
    crmCommisionFiMgr: numeric("CRMCommisionFIMgr", {
      precision: 10,
      scale: 2,
    }),
    crmCommisionSp1: numeric("CRMCommisionSP1", { precision: 10, scale: 2 }),
    crmCommisionSp2: numeric("CRMCommisionSP2", { precision: 10, scale: 2 }),
    crmCommisionSp3: numeric("CRMCommisionSP3", { precision: 10, scale: 2 }),
    crmCommisionSalesMgr: numeric("CRMCommisionSalesMgr", {
      precision: 10,
      scale: 2,
    }),
    crmCommisionTotal: numeric("CRMCommisionTotal", {
      precision: 10,
      scale: 2,
    }),
    crmfiMgrId: varchar("CRMFIMgrId", { length: 50 }),
    crmfiMgrName: varchar("CRMFIMgrName", { length: 50 }),
    crmFlag: smallint("CRMFlag"),
    vin: varchar("VIN", { length: 17 }),
    vehInventoryCompany: smallint("VehInventoryCompany"),
    vehSaleCompany: smallint("VehSaleCompany"),
    vehicleMileage: integer("VehicleMileage"),
    waqNumber: integer("WAQNumber"),
    warrantyFee: numeric("WarrantyFee", { precision: 10, scale: 2 }),
    weOweBackSaleTotal: numeric("WeOweBackSaleTotal", {
      precision: 10,
      scale: 2,
    }),
    weOweCostTotal: numeric("WeOweCostTotal", { precision: 10, scale: 2 }),
    weOweFrontGrossSales: numeric("WeOweFrontGrossSales", {
      precision: 10,
      scale: 2,
    }),
    weOweResidualTableTotal: numeric("WeOweResidualTableTotal", {
      precision: 10,
      scale: 2,
    }),
    weOweResidualTotal: numeric("WeOweResidualTotal", {
      precision: 10,
      scale: 2,
    }),
    weOweSaleHardTotal: numeric("WeOweSaleHardTotal", {
      precision: 10,
      scale: 2,
    }),
    weOweSaleSoftTotal: numeric("WeOweSaleSoftTotal", {
      precision: 10,
      scale: 2,
    }),
    weOweSaleTotal: numeric("WeOweSaleTotal", { precision: 10, scale: 2 }),
    year: integer("Year"),
    zipOrPostalCode: varchar("ZipOrPostalCode", { length: 20 }),
    securityDepositAmount: numeric("SecurityDepositAmount", {
      precision: 10,
      scale: 2,
    }),
    sellRateApr: numeric("SellRateAPR", { precision: 10, scale: 2 }),
    sellRateAddOn: numeric("SellRateAddOn", { precision: 10, scale: 2 }),
    sellRateLmf: numeric("SellRateLMF", { precision: 10, scale: 2 }),
    serviceTaxAmount: numeric("ServiceTaxAmount", { precision: 10, scale: 2 }),
    leaseEndPercentageRate: smallint("LeaseEndPercentageRate"),
    leaseEndValue: numeric("LeaseEndValue", { precision: 10, scale: 2 }),
    leaseMileageAllowance: integer("LeaseMileageAllowance"),
    leasePayment: numeric("LeasePayment", { precision: 10, scale: 2 }),
    leaseType: varchar("LeaseType", { length: 2 }),
    levelizedLifeAmount: numeric("LevelizedLifeAmount", {
      precision: 10,
      scale: 2,
    }),
    levelizedLifeDealerComm: numeric("LevelizedLifeDealerComm", {
      precision: 10,
      scale: 2,
    }),
    levelizedLifeIncome: numeric("LevelizedLifeIncome", {
      precision: 10,
      scale: 2,
    }),
    lienHolderAddress: varchar("LienHolderAddress", { length: 100 }),
    lienHolderCity: varchar("LienHolderCity", { length: 50 }),
    lienHolderName: varchar("LienHolderName", { length: 100 }),
    lienHolderName2: varchar("LienHolderName2", { length: 100 }),
    lienHolderPhone: varchar("LienHolderPhone", { length: 20 }),
    lienHolderState: varchar("LienHolderState", { length: 2 }),
    lienHolderZip: varchar("LienHolderZip", { length: 20 }),
    addToCapCostFee4ProfitType: varchar("AddToCapCostFee4ProfitType", {
      length: 2,
    }),
    addToCapCostFee5Amount: numeric("AddToCapCostFee5Amount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee5CostAmount: numeric("AddToCapCostFee5CostAmount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee5Name: varchar("AddToCapCostFee5Name", { length: 25 }),
    addToCapCostFee5ProfitType: varchar("AddToCapCostFee5ProfitType", {
      length: 2,
    }),
    addToCapCostFee6Amount: numeric("AddToCapCostFee6Amount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee6CostAmount: numeric("AddToCapCostFee6CostAmount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee6Name: varchar("AddToCapCostFee6Name", { length: 25 }),
    addToCapCostFee6ProfitType: varchar("AddToCapCostFee6ProfitType", {
      length: 2,
    }),
    addToCapCostFee7Amount: numeric("AddToCapCostFee7Amount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee7CostAmount: numeric("AddToCapCostFee7CostAmount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee7Name: varchar("AddToCapCostFee7Name", { length: 25 }),
    addToCapCostFee7ProfitType: varchar("AddToCapCostFee7ProfitType", {
      length: 2,
    }),
    address: varchar("Address", { length: 100 }),
    adjustedCapCost: numeric("AdjustedCapCost", { precision: 10, scale: 2 }),
    adjustedCostofVehicle: numeric("AdjustedCostofVehicle", {
      precision: 10,
      scale: 2,
    }),
    adjustmentsDealerDefined: numeric("AdjustmentsDealerDefined", {
      precision: 10,
      scale: 2,
    }),
    adjustmentsRopo: numeric("AdjustmentsROPO", { precision: 10, scale: 2 }),
    adjustmentsStandard: numeric("AdjustmentsStandard", {
      precision: 10,
      scale: 2,
    }),
    age: smallint("Age"),
    amountDueAtStart: numeric("AmountDueAtStart", { precision: 10, scale: 2 }),
    annualFee1Amount: numeric("AnnualFee1Amount", { precision: 10, scale: 2 }),
    annualFee1Name: varchar("AnnualFee1Name", { length: 25 }),
    annualFee2Amount: numeric("AnnualFee2Amount", { precision: 10, scale: 2 }),
    annualFee2Name: varchar("AnnualFee2Name", { length: 25 }),
    annualFee3Amount: numeric("AnnualFee3Amount", { precision: 10, scale: 2 }),
    annualFee3Name: varchar("AnnualFee3Name", { length: 25 }),
    annualFee3DealerCommBase: numeric("AnnualFee3DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    annualFee4Amount: numeric("AnnualFee4Amount", { precision: 10, scale: 2 }),
    annualFee4Name: varchar("AnnualFee4Name", { length: 25 }),
    annualFee4DealerCommBase: numeric("AnnualFee4DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    annualFee5Amount: numeric("AnnualFee5Amount", { precision: 10, scale: 2 }),
    annualFee5Name: varchar("AnnualFee5Name", { length: 25 }),
    annualFee5DealerCommBase: numeric("AnnualFee5DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    assnSlsperson: varchar("AssnSlsperson", { length: 50 }),
    insurance1Term: integer("Insurance1Term"),
    insurance2Deductible: numeric("Insurance2Deductible", {
      precision: 10,
      scale: 2,
    }),
    insurance2Limit: numeric("Insurance2Limit", { precision: 10, scale: 2 }),
    insurance2LimitMiles: integer("Insurance2LimitMiles"),
    insurance2Name: varchar("Insurance2Name", { length: 50 }),
    insurance2Term: integer("Insurance2Term"),
    insurance3Deductible: numeric("Insurance3Deductible", {
      precision: 10,
      scale: 2,
    }),
    insurance3Limit: numeric("Insurance3Limit", { precision: 10, scale: 2 }),
    insurance3LimitMiles: integer("Insurance3LimitMiles"),
    insurance3Name: varchar("Insurance3Name", { length: 50 }),
    insurance3Term: integer("Insurance3Term"),
    insuranceCommDlr: numeric("InsuranceCommDlr", { precision: 10, scale: 2 }),
    insuranceTypeCode: varchar("InsuranceTypeCode", { length: 50 }),
    lstgstAmount: numeric("LSTGSTAmount", { precision: 10, scale: 2 }),
    lstgstRate: numeric("LSTGSTRate", { precision: 5, scale: 4 }),
    lstgstRateFlat: numeric("LSTGSTRateFlat", { precision: 10, scale: 2 }),
    lastPayAmount: numeric("LastPayAmount", { precision: 10, scale: 2 }),
    lastPayDate: date("LastPayDate"),
    outTheDoorPrice: numeric("OutTheDoorPrice", { precision: 10, scale: 2 }),
    paymentAmt: numeric("PaymentAmt", { precision: 10, scale: 2 }),
    paymentCode: varchar("PaymentCode", { length: 50 }),
    paymentStyle: varchar("PaymentStyle", { length: 50 }),
    payments: integer("Payments"),
    pickupDate1: date("PickupDate1"),
    pickupDate2: date("PickupDate2"),
    pickupDate3: date("PickupDate3"),
    pickupPay1: numeric("PickupPay1", { precision: 10, scale: 2 }),
    pickupPay2: numeric("PickupPay2", { precision: 10, scale: 2 }),
    pickupPay3: numeric("PickupPay3", { precision: 10, scale: 2 }),
    extWarrantyExpMilesLease: integer("ExtWarrantyExpMilesLease"),
    extWarrantyTermLease: integer("ExtWarrantyTermLease"),
    fiDealType: varchar("FIDealType", { length: 5 }),
    fiIncome: numeric("FIIncome", { precision: 10, scale: 2 }),
    fiMgr1: varchar("FIMgr1", { length: 50 }),
    fiMgr2: varchar("FIMgr2", { length: 50 }),
    feeOption10Amount: numeric("FeeOption10Amount", {
      precision: 10,
      scale: 2,
    }),
    feeOption10Cost: numeric("FeeOption10Cost", { precision: 10, scale: 2 }),
    feeOption10Name: varchar("FeeOption10Name", { length: 50 }),
    feeOption10ProfitType: varchar("FeeOption10ProfitType", { length: 5 }),
    feeOption1Amount: numeric("FeeOption1Amount", { precision: 10, scale: 2 }),
    feeOption1Cost: numeric("FeeOption1Cost", { precision: 10, scale: 2 }),
    feeOption1Name: varchar("FeeOption1Name", { length: 50 }),
    feeOption1ProfitType: varchar("FeeOption1ProfitType", { length: 5 }),
    feeOption2Amount: numeric("FeeOption2Amount", { precision: 10, scale: 2 }),
    feeOption2Cost: numeric("FeeOption2Cost", { precision: 10, scale: 2 }),
    feeOption2Name: varchar("FeeOption2Name", { length: 50 }),
    feeOption2ProfitType: varchar("FeeOption2ProfitType", { length: 5 }),
    rebateAmount: numeric("RebateAmount", { precision: 10, scale: 2 }),
    slsDealType: varchar("SLSDealType", { length: 50 }),
    saleCreditSp1: numeric("SaleCreditSP1", { precision: 10, scale: 2 }),
    saleCreditSp2: numeric("SaleCreditSP2", { precision: 10, scale: 2 }),
    saleCreditSp3: numeric("SaleCreditSP3", { precision: 10, scale: 2 }),
    salePriceWithWeOwes: numeric("SalePriceWithWeOwes", {
      precision: 10,
      scale: 2,
    }),
    saleType: varchar("SaleType", { length: 50 }),
    salesAccount: varchar("SalesAccount", { length: 50 }),
    salesDate: date("SalesDate"),
    salesManagementDealType: varchar("SalesManagementDealType", { length: 50 }),
    salesMgr: varchar("SalesMgr", { length: 50 }),
    salesperson1: varchar("Salesperson1", { length: 50 }),
    salesperson2: varchar("Salesperson2", { length: 50 }),
    salesperson3: varchar("Salesperson3", { length: 50 }),
    crmsp1Id: varchar("CRMSP1Id", { length: 50 }),
    crmsp1Name: varchar("CRMSP1Name", { length: 50 }),
    crmsp2Id: varchar("CRMSP2Id", { length: 50 }),
    crmsp2Name: varchar("CRMSP2Name", { length: 50 }),
    crmsp3Id: varchar("CRMSP3Id", { length: 50 }),
    crmsp3Name: varchar("CRMSP3Name", { length: 50 }),
    crmSaleCreditClosingMgr: numeric("CRMSaleCreditClosingMgr", {
      precision: 10,
      scale: 2,
    }),
    crmSaleCreditFiMgr: numeric("CRMSaleCreditFIMgr", {
      precision: 10,
      scale: 2,
    }),
    crmSaleCreditSp1: numeric("CRMSaleCreditSP1", { precision: 10, scale: 2 }),
    crmSaleCreditSp2: numeric("CRMSaleCreditSP2", { precision: 10, scale: 2 }),
    crmSaleCreditSp3: numeric("CRMSaleCreditSP3", { precision: 10, scale: 2 }),
    crmSaleCreditSalesMgr: numeric("CRMSaleCreditSalesMgr", {
      precision: 10,
      scale: 2,
    }),
    crmSaleType: varchar("CRMSaleType", { length: 50 }),
    crmSalesCreditTotal: numeric("CRMSalesCreditTotal", {
      precision: 10,
      scale: 2,
    }),
    crmSalesMgrId: varchar("CRMSalesMgrId", { length: 50 }),
    crmSalesMgrName: varchar("CRMSalesMgrName", { length: 50 }),
    crmSpiffClosingMgr: numeric("CRMSpiffClosingMgr", {
      precision: 10,
      scale: 2,
    }),
    crmSpiffFiMgr: numeric("CRMSpiffFIMgr", { precision: 10, scale: 2 }),
    crmSpiffSp1: numeric("CRMSpiffSP1", { precision: 10, scale: 2 }),
    crmSpiffSp2: numeric("CRMSpiffSP2", { precision: 10, scale: 2 }),
    crmSpiffSp3: numeric("CRMSpiffSP3", { precision: 10, scale: 2 }),
    crmSpiffSalesMgr: numeric("CRMSpiffSalesMgr", { precision: 10, scale: 2 }),
    crmSpiffTotal: numeric("CRMSpiffTotal", { precision: 10, scale: 2 }),
    calcMethod: varchar("CalcMethod", { length: 50 }),
    cashCapReduction: numeric("CashCapReduction", { precision: 10, scale: 2 }),
    cashDown: numeric("CashDown", { precision: 10, scale: 2 }),
    cashPrice: numeric("CashPrice", { precision: 10, scale: 2 }),
    city: varchar("City", { length: 50 }),
    closingMgr: varchar("ClosingMgr", { length: 50 }),
    coAddress: varchar("CoAddress", { length: 100 }),
    coBusinessPhone: varchar("CoBusinessPhone", { length: 20 }),
    coBuyer: varchar("CoBuyer", { length: 50 }),
    coCity: varchar("CoCity", { length: 50 }),
    coCounty: varchar("CoCounty", { length: 50 }),
    coCustNo: varchar("CoCustNo", { length: 50 }),
    coHomePhone: varchar("CoHomePhone", { length: 20 }),
    coName1: varchar("CoName1", { length: 50 }),
    coState: varchar("CoState", { length: 2 }),
    coZipOrPostalCode: varchar("CoZipOrPostalCode", { length: 20 }),
    dealerDefined6: varchar("DealerDefined6", { length: 50 }),
    dealerDefined7: varchar("DealerDefined7", { length: 50 }),
    dealerDefined8: varchar("DealerDefined8", { length: 50 }),
    deliveryCoord: varchar("DeliveryCoord", { length: 50 }),
    depositAmount: numeric("DepositAmount", { precision: 10, scale: 2 }),
    depositType: varchar("DepositType", { length: 50 }),
    dueOnDelivery: numeric("DueOnDelivery", { precision: 10, scale: 2 }),
    frontEndGrossProfit: numeric("FrontEndGrossProfit", {
      precision: 10,
      scale: 2,
    }),
    frontGross: numeric("FrontGross", { precision: 10, scale: 2 }),
    frontWeOwes: numeric("FrontWeOwes", { precision: 10, scale: 2 }),
    frontWeOwesGrossCost: numeric("FrontWeOwesGrossCost", {
      precision: 10,
      scale: 2,
    }),
    frontWeOwesGrossSales: numeric("FrontWeOwesGrossSales", {
      precision: 10,
      scale: 2,
    }),
    glVehicleCost: numeric("GLVehicleCost", { precision: 10, scale: 2 }),
    grossProfit: numeric("GrossProfit", { precision: 10, scale: 2 }),
    homePhone: varchar("HomePhone", { length: 20 }),
    incentiveDealer: numeric("IncentiveDealer", { precision: 10, scale: 2 }),
    incentiveProgram: varchar("IncentiveProgram", { length: 50 }),
    mbiCarrier: varchar("MBICarrier", { length: 50 }),
    mbiCost: numeric("MBICost", { precision: 10, scale: 2 }),
    mbiDeductible: numeric("MBIDeductible", { precision: 10, scale: 2 }),
    mbiEligComment: varchar("MBIEligComment", { length: 200 }),
    mbiEligFlag: varchar("MBIEligFlag", { length: 5 }),
    mbiFee: numeric("MBIFee", { precision: 10, scale: 2 }),
    mbiIncome: numeric("MBIIncome", { precision: 10, scale: 2 }),
    mbiLimit: numeric("MBILimit", { precision: 10, scale: 2 }),
    mbiLimitMax: numeric("MBILimitMax", { precision: 10, scale: 2 }),
    mbiName: varchar("MBIName", { length: 50 }),
    ahCost: numeric("AHCost", { precision: 10, scale: 2 }),
    ahIncome: numeric("AHIncome", { precision: 10, scale: 2 }),
    ahPremium: numeric("AHPremium", { precision: 10, scale: 2 }),
    apr: numeric("APR", { precision: 5, scale: 2 }),
    accountingAccount: varchar("AccountingAccount", { length: 50 }),
    accountingDate: date("AccountingDate"),
    addCapCostFee3DealerCommBase: numeric("AddCapCostFee3DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    addCapCostFee4DealerCommBase: numeric("AddCapCostFee4DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    addCapCostFee5DealerCommBase: numeric("AddCapCostFee5DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    addCapCostFee6DealerCommBase: numeric("AddCapCostFee6DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    addCapCostFee7DealerCommBase: numeric("AddCapCostFee7DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    addToCapAmount: numeric("AddToCapAmount", { precision: 10, scale: 2 }),
    addToCapCostFee1Amount: numeric("AddToCapCostFee1Amount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee1CostAmount: numeric("AddToCapCostFee1CostAmount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee1Name: varchar("AddToCapCostFee1Name", { length: 50 }),
    addToCapCostFee1ProfitType: varchar("AddToCapCostFee1ProfitType", {
      length: 5,
    }),
    addToCapCostFee2Amount: numeric("AddToCapCostFee2Amount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee2CostAmount: numeric("AddToCapCostFee2CostAmount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee2Name: varchar("AddToCapCostFee2Name", { length: 50 }),
    addToCapCostFee2ProfitType: varchar("AddToCapCostFee2ProfitType", {
      length: 5,
    }),
    addToCapCostFee3Amount: numeric("AddToCapCostFee3Amount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee3CostAmount: numeric("AddToCapCostFee3CostAmount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee3Name: varchar("AddToCapCostFee3Name", { length: 50 }),
    addToCapCostFee3ProfitType: varchar("AddToCapCostFee3ProfitType", {
      length: 5,
    }),
    addToCapCostFee4Amount: numeric("AddToCapCostFee4Amount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee4CostAmount: numeric("AddToCapCostFee4CostAmount", {
      precision: 10,
      scale: 2,
    }),
    addToCapCostFee4Flag: varchar("AddToCapCostFee4Flag", { length: 5 }),
    addToCapCostFee4Name: varchar("AddToCapCostFee4Name", { length: 50 }),
    email1: varchar("Email1", { length: 100 }),
    email1Desc: varchar("Email1Desc", { length: 100 }),
    email2: varchar("Email2", { length: 100 }),
    email2Desc: varchar("Email2Desc", { length: 100 }),
    email3: varchar("Email3", { length: 100 }),
    email3Desc: varchar("Email3Desc", { length: 100 }),
    errorLevel: integer("ErrorLevel"),
    errorMessage: varchar("ErrorMessage", { length: 255 }),
    miscellaneous1: varchar("Miscellaneous1", { length: 50 }),
    miscellaneous2: varchar("Miscellaneous2", { length: 50 }),
    model: varchar("Model", { length: 50 }),
    modelName: text("ModelName"),
    modelNo: varchar("ModelNo", { length: 50 }),
    modelType: varchar("ModelType", { length: 50 }),
    name: varchar("Name", { length: 50 }),
    name1: varchar("Name1", { length: 50 }),
    netTrade1: numeric("NetTrade1", { precision: 12, scale: 2 }),
    netTrade2: numeric("NetTrade2", { precision: 12, scale: 2 }),
    optionsCommDlr: numeric("OptionsCommDlr", { precision: 12, scale: 2 }),
    term: integer("Term"),
    texasGapInsuranceAmount: numeric("TexasGAPInsuranceAmount", {
      precision: 12,
      scale: 2,
    }),
    texasGapInsuranceDealerCommissionBase: numeric(
      "TexasGAPInsuranceDealerCommissionBase",
      { precision: 12, scale: 2 },
    ),
    totalAnnFees: numeric("TotalAnnFees", { precision: 12, scale: 2 }),
    totalCapReduction: numeric("TotalCapReduction", {
      precision: 12,
      scale: 2,
    }),
    totalCashSurplus: numeric("TotalCashSurplus", { precision: 12, scale: 2 }),
    totalCommission: numeric("TotalCommission", { precision: 12, scale: 2 }),
    totalCommissionSp1: numeric("TotalCommissionSP1", {
      precision: 12,
      scale: 2,
    }),
    totalCommissionSp2: numeric("TotalCommissionSP2", {
      precision: 12,
      scale: 2,
    }),
    totalDown: numeric("TotalDown", { precision: 12, scale: 2 }),
    totalFinancedFeeOptions: numeric("TotalFinancedFeeOptions", {
      precision: 12,
      scale: 2,
    }),
    totalGross: numeric("TotalGross", { precision: 12, scale: 2 }),
    totalInitFees: numeric("TotalInitFees", { precision: 12, scale: 2 }),
    totalInsurancePremiums: numeric("TotalInsurancePremiums", {
      precision: 12,
      scale: 2,
    }),
    totalOfMonthlyPayments: numeric("TotalOfMonthlyPayments", {
      precision: 12,
      scale: 2,
    }),
    totalOptionsFees: numeric("TotalOptionsFees", { precision: 12, scale: 2 }),
    totalTaxableFees: numeric("TotalTaxableFees", { precision: 12, scale: 2 }),
    totalTradeAllowance: numeric("TotalTradeAllowance", {
      precision: 12,
      scale: 2,
    }),
    totalTradesAcv: numeric("TotalTradesACV", { precision: 12, scale: 2 }),
    totalTradesNet: numeric("TotalTradesNet", { precision: 12, scale: 2 }),
    totalTradesOver: numeric("TotalTradesOver", { precision: 12, scale: 2 }),
    totalTradesPayoff: numeric("TotalTradesPayoff", {
      precision: 12,
      scale: 2,
    }),
    purchaseFlexibleTax1Amount: numeric("PurchaseFlexibleTax1Amount", {
      precision: 12,
      scale: 2,
    }),
    purchaseFlexibleTax1Base: numeric("PurchaseFlexibleTax1Base", {
      precision: 12,
      scale: 2,
    }),
    purchaseFlexibleTax1Max: numeric("PurchaseFlexibleTax1Max", {
      precision: 12,
      scale: 2,
    }),
    purchaseFlexibleTax1MaxCode: varchar("PurchaseFlexibleTax1MaxCode", {
      length: 50,
    }),
    purchaseFlexibleTax1Name: varchar("PurchaseFlexibleTax1Name", {
      length: 50,
    }),
    purchaseFlexibleTax1Rate: numeric("PurchaseFlexibleTax1Rate", {
      precision: 5,
      scale: 4,
    }),
    purchaseFlexibleTax2Amount: numeric("PurchaseFlexibleTax2Amount", {
      precision: 12,
      scale: 2,
    }),
    purchaseFlexibleTax2Base: numeric("PurchaseFlexibleTax2Base", {
      precision: 12,
      scale: 2,
    }),
    purchaseFlexibleTax2Max: numeric("PurchaseFlexibleTax2Max", {
      precision: 12,
      scale: 2,
    }),
    purchaseFlexibleTax2MaxCode: varchar("PurchaseFlexibleTax2MaxCode", {
      length: 50,
    }),
    purchaseFlexibleTax2Name: varchar("PurchaseFlexibleTax2Name", {
      length: 50,
    }),
    purchaseFlexibleTax2Rate: numeric("PurchaseFlexibleTax2Rate", {
      precision: 5,
      scale: 4,
    }),
    purchaseMbiCost: numeric("PurchaseMBICost", { precision: 12, scale: 2 }),
    purchaseMbisp2CommAmount: numeric("PurchaseMBISP2CommAmount", {
      precision: 12,
      scale: 2,
    }),
    color: varchar("Color", { length: 50 }),
    commOnSaleDlr: numeric("CommOnSaleDlr", { precision: 12, scale: 2 }),
    commissionPack: numeric("CommissionPack", { precision: 12, scale: 2 }),
    commissionSp1: numeric("CommissionSP1", { precision: 12, scale: 2 }),
    commissionSp2: numeric("CommissionSP2", { precision: 12, scale: 2 }),
    commissionSp3: numeric("CommissionSP3", { precision: 12, scale: 2 }),
    cont1Date: date("Cont1Date"),
    cont1Reason: varchar("Cont1Reason", { length: 50 }),
    cont2Date: date("Cont2Date"),
    cont2Reason: varchar("Cont2Reason", { length: 50 }),
    contractDate: date("ContractDate"),
    costPrice: numeric("CostPrice", { precision: 12, scale: 2 }),
    county: varchar("County", { length: 50 }),
    custNo: varchar("CustNo", { length: 20 }),
    custOrCompanyCode: varchar("CustOrCompanyCode", { length: 50 }),
    customerCashDown: numeric("CustomerCashDown", { precision: 12, scale: 2 }),
    customerComments: text("CustomerComments"),
    initFee10DealerCommissionBase: numeric("InitFee10DealerCommissionBase", {
      precision: 12,
      scale: 2,
    }),
  },
  (table) => {
    return {
      dealsPkey: primaryKey({
        columns: [table.fiWipStatusCode, table.branch, table.hostItemId],
        name: "deals_pkey",
      }),
    };
  },
);

export const vehicles = pgTable("vehicles", {
  vin: varchar("vin", { length: 17 }).primaryKey(), // VINs are typically 17 characters long
  primaryDriverNo: text("primary_driver_no"),
  accountingAccount: text("accounting_account"),
  model: text("model"),
  modelName: text("model_name"),
  modelType: text("model_type"),
  trimLevel: text("trim_level"),
  engineDescription: text("engine_description"),
  engineNo: text("engine_no"),
  color: text("color"),
  interiorColor: text("interior_color"),
  bodyStyle: text("body_style"),
  fuelType: text("fuel_type"),
  year: integer("year"),
  make: text("make"),
  makeName: text("make_name"),
  manufacturer: text("manufacturer"),
  plantOfManufacture: text("plant_of_manufacture"),
  numberOfDoors: integer("number_of_doors"),
  cylinderNo: integer("cylinder_no"),
  commissionPrice: numeric("commission_price", { precision: 10, scale: 2 }),
  retailPriceUpdateDate: date("retail_price_update_date"),
  vehicleSoldDate: date("vehicle_sold_date"),
  soldDate: date("sold_date"),
  mileage: integer("mileage"),
  soldMileage: integer("sold_mileage"),
  stockNo: text("stock_no"),
  stockType: text("stock_type"),
  status: text("status"),
  balance: numeric("balance", { precision: 10, scale: 2 }),
  price1: numeric("price1", { precision: 10, scale: 2 }),
  price2: numeric("price2", { precision: 10, scale: 2 }),
  options: text("options"),
  orderDate: date("order_date"),
  expectedDeliveryDate: date("expected_delivery_date"),
  actualCashValue: numeric("actual_cash_value", { precision: 10, scale: 2 }),
  advertisedPrice: numeric("advertised_price", { precision: 10, scale: 2 }),
  advertisedPriceExpDate: date("advertised_price_exp_date"),
  advertisedPriceStartDate: date("advertised_price_start_date"),
  totalOptionsCost: numeric("total_options_cost", { precision: 10, scale: 2 }),
  totalOptionsInvoice: numeric("total_options_invoice", {
    precision: 10,
    scale: 2,
  }),
  totalOptionsRetail: numeric("total_options_retail", {
    precision: 10,
    scale: 2,
  }),
  invoicePackAmount: numeric("invoice_pack_amount", {
    precision: 10,
    scale: 2,
  }),
  commissionPackAmount: numeric("commission_pack_amount", {
    precision: 10,
    scale: 2,
  }),
  commissionPackPercent: numeric("commission_pack_percent", {
    precision: 10,
    scale: 2,
  }),
  entryDate: date("entry_date"),
  lastActivityDate: date("last_activity_date"),
});
