import {
  pgTable,
  varchar,
  primaryKey,
  numeric,
  integer,
  smallint,
  date,
  bigint,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const GLJE = pgTable(
  "GLJE",
  {
    hostItemId: text("HostItemID").notNull(),
    accountingDate: date("AccountingDate").notNull(),
    accountNumber: text("AccountNumber").notNull(),
    accountNumberRight: text("AccountNumberRight").notNull(),
    companyID: text("CompanyID").notNull(),
    companyIDRight: text("CompanyIDRight").notNull(),
    control: text("Control"),
    control2: text("Control2"),
    controlRight: text("ControlRight"),
    control2Right: text("Control2Right"),
    controlType: integer("ControlType"),
    controlType2: integer("ControlType2"),
    currentMonth: text("CurrentMonth"),
    detailDescription: text("DetailDescription"),
    distillControlType: integer("DistillControlType"),
    distillControlType2: integer("DistillControlType2"),
    errorLevel: integer("ErrorLevel"),
    errorMessage: text("ErrorMessage"),
    journalID: integer("JournalID"),
    journalIDRight: integer("JournalIDRight"),
    postingAmount: numeric("PostingAmount", { precision: 10, scale: 2 }),
    postingSequence: integer("PostingSequence"),
    postingTime: bigint("PostingTime", { mode: "number" }),
    prodNo: text("ProdNo"),
    prodNo2: text("ProdNo2"),
    prodNoRight: text("ProdNoRight"),
    prodNo2Right: text("ProdNo2Right"),
    prodType: integer("ProdType"),
    prodType2: integer("ProdType2"),
    refer: text("Refer"),
    referRight: text("ReferRight"),
    scheduleNumber: text("ScheduleNumber"),
    statCount: integer("StatCount"),
  },
  (table) => {
    return {
      accountingRecordsPkey: primaryKey({
        columns: [table.hostItemId, table.accountingDate, table.accountNumber],
        name: "GLJE_pkey",
      }),
    };
  },
);

export const COA = pgTable(
  "COA",
  {
    statCountType: text("StatCountType"),
    pattern: text("Pattern"),
    postDescFlag: text("PostDescFlag"),
    techFlag: text("TechFlag"),
    hostItemId: text("HostItemID").notNull(),
    accountDescription: text("AccountDescription"),
    accountNumber: text("AccountNumber").notNull(),
    accountNumberRight: text("AccountNumberRight").notNull(),
    accountType: text("AccountType"),
    acctSubType: text("AcctSubType"),
    acctUpdDate: date("AcctUpdDate"),
    beginDate: date("BeginDate"),
    cntl2Type: text("Cntl2Type"),
    cntlType: text("CntlType"),
    companyID: text("CompanyID").notNull(),
    companyIDRight: text("CompanyIDRight").notNull(),
    deptID: text("DeptID"),
    deptIDRight: text("DeptIDRight"),
    endDate: date("EndDate"),
    errorLevel: integer("ErrorLevel"),
    errorMessage: text("ErrorMessage"),
    franchiseId: text("FranchiseId"),
    bfSched: text("BFSched"),
    dfSched: text("DFSched"),
    incBalGrp: text("IncBalGrp"),
    incBalGrpDesc: text("IncBalGrpDesc"),
    incBalSubGrp: text("IncBalSubGrp"),
    incBalSubGrpDesc: text("IncBalSubGrpDesc"),
    prodType: integer("ProdType"),
    rptGrp: text("RptGrp"),
    rptGrpDesc: text("RptGrpDesc"),
    unaGrp: text("UnaGrp"),
    unaGrpDesc: text("UnaGrpDesc"),
    chain: text("Chain"),
  },
  (table) => {
    return {
      financialRecordsPkey: primaryKey({
        columns: [table.hostItemId, table.accountNumber, table.companyID],
        name: "COA_pkey",
      }),
    };
  },
);

export const dealInitialfee = pgTable(
  "deal_initialfee",
  {
    FiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    Branch: varchar("Branch", { length: 20 }).notNull(),
    HostItemID: varchar("HostItemID", { length: 20 }).notNull(),
    InitialFee4ProfitType: varchar("InitialFee4ProfitType", { length: 1 }),
  },
  (table) => {
    return {
      DealInitialfeePkey: primaryKey({
        columns: [table.FiWipStatusCode, table.Branch, table.HostItemID],
        name: "deal_initialfee_pkey",
      }),
    };
  },
);

export const dealTradedealerdefined = pgTable(
  "deal_tradedealerdefined",
  {
    FiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    Branch: varchar("Branch", { length: 20 }).notNull(),
    HostItemID: varchar("HostItemID", { length: 20 }).notNull(),
    TradeDealerDefined1: varchar("TradeDealerDefined1", { length: 17 }),
    TradeDealerDefined2: varchar("TradeDealerDefined2", { length: 17 }),
    TradeDealerDefined3: varchar("TradeDealerDefined3", { length: 17 }),
    TradeDealerDefined4: varchar("TradeDealerDefined4", { length: 17 }),
    TradeDealerDefined5: varchar("TradeDealerDefined5", { length: 17 }),
    TradeDealerDefined6: varchar("TradeDealerDefined6", { length: 17 }),
    TradeDealerDefined7: varchar("TradeDealerDefined7", { length: 17 }),
    TradeDealerDefined8: varchar("TradeDealerDefined8", { length: 17 }),
  },
  (table) => {
    return {
      DealTradedealerdefinedPkey: primaryKey({
        columns: [table.FiWipStatusCode, table.Branch, table.HostItemID],
        name: "deal_tradedealerdefined_pkey",
      }),
    };
  },
);

export const dealTrade2 = pgTable(
  "deal_trade2",
  {
    FiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    Branch: varchar("Branch", { length: 20 }).notNull(),
    HostItemID: varchar("HostItemID", { length: 20 }).notNull(),
    Trade2Acv: varchar("Trade2ACV", { length: 17 }),
    Trade2Color: varchar("Trade2Color", { length: 17 }),
    Trade2Gross: numeric("Trade2Gross", { precision: 10, scale: 2 }),
    Trade2Make: varchar("Trade2Make", { length: 50 }),
    Trade2Mileage: integer("Trade2Mileage"),
    Trade2Model: varchar("Trade2Model", { length: 17 }),
    Trade2ModelName: varchar("Trade2ModelName", { length: 17 }),
    Trade2ModelNo: varchar("Trade2ModelNo", { length: 17 }),
    Trade2ModelType: varchar("Trade2ModelType", { length: 17 }),
    Trade2Over: numeric("Trade2Over", { precision: 10, scale: 2 }),
    Trade2PayOff: numeric("Trade2PayOff", { precision: 10, scale: 2 }),
    Trade2Stock: varchar("Trade2Stock", { length: 50 }),
    Trade2Style: varchar("Trade2Style", { length: 15 }),
    Trade2Vin: varchar("Trade2VIN", { length: 17 }),
    Trade2Year: integer("Trade2Year"),
  },
  (table) => {
    return {
      DealTrade2Pkey: primaryKey({
        columns: [table.FiWipStatusCode, table.Branch, table.HostItemID],
        name: "deal_trade2_pkey",
      }),
    };
  },
);

export const dealTrade1 = pgTable(
  "deal_trade1",
  {
    FiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    Branch: varchar("Branch", { length: 20 }).notNull(),
    HostItemID: varchar("HostItemID", { length: 20 }).notNull(),
    Trade1Model: varchar("Trade1Model", { length: 50 }),
    Trade1ModelName: varchar("Trade1ModelName", { length: 50 }),
    Trade1ModelNo: varchar("Trade1ModelNo", { length: 50 }),
    Trade1ModelType: varchar("Trade1ModelType", { length: 50 }),
    Trade1Over: numeric("Trade1Over", { precision: 10, scale: 2 }),
    Trade1PayOff: numeric("Trade1PayOff", { precision: 10, scale: 2 }),
    Trade1Stock: varchar("Trade1Stock", { length: 50 }),
    Trade1Style: varchar("Trade1Style", { length: 15 }),
    Trade1Vin: varchar("Trade1VIN", { length: 17 }),
    Trade1Year: integer("Trade1Year"),
    Trade1Acv: numeric("Trade1ACV", { precision: 12, scale: 2 }),
    Trade1Color: varchar("Trade1Color", { length: 50 }),
    Trade1Gross: numeric("Trade1Gross", { precision: 12, scale: 2 }),
    Trade1Make: varchar("Trade1Make", { length: 50 }),
    Trade1MakeName: varchar("Trade1MakeName", { length: 50 }),
    Trade1Mileage: integer("Trade1Mileage"),
  },
  (table) => {
    return {
      DealTrade1Pkey: primaryKey({
        columns: [table.FiWipStatusCode, table.Branch, table.HostItemID],
        name: "deal_trade1_pkey",
      }),
    };
  },
);

export const dealFiaux = pgTable(
  "deal_fiaux",
  {
    FiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    Branch: varchar("Branch", { length: 20 }).notNull(),
    HostItemID: varchar("HostItemID", { length: 20 }).notNull(),
    FiAux1: varchar("FiAux1", { length: 50 }),
    FiAux40: integer("FiAux40"),
    FiAux41: integer("FiAux41"),
    FiAux42: integer("FiAux42"),
    FiAux43: integer("FiAux43"),
    FiAux44: integer("FiAux44"),
    FiAux45: integer("FiAux45"),
    FiAux46: integer("FiAux46"),
    FiAux47: integer("FiAux47"),
    FiAux48: integer("FiAux48"),
    FiAux49: integer("FiAux49"),
    FiAux5: integer("FiAux5"),
    FiAux50: varchar("FiAux50", { length: 50 }),
    FiAux6: varchar("FiAux6", { length: 50 }),
    FiAux7: integer("FiAux7"),
    FiAux8: varchar("FiAux8", { length: 50 }),
    FiAux9: varchar("FiAux9", { length: 50 }),
    FiAux10: varchar("FiAux10", { length: 50 }),
    FiAux11: varchar("FiAux11", { length: 50 }),
    FiAux12: varchar("FiAux12", { length: 50 }),
    FiAux13: varchar("FiAux13", { length: 50 }),
    FiAux14: varchar("FiAux14", { length: 50 }),
  },
  (table) => {
    return {
      DealFiauxPkey: primaryKey({
        columns: [table.FiWipStatusCode, table.Branch, table.HostItemID],
        name: "deal_fiaux_pkey",
      }),
    };
  },
);

export const customers = pgTable(
  "customers",
  {
    hostItemId: varchar("HostItemID", { length: 40 }).notNull(),
    custNo: varchar("CustNo", { length: 17 }).notNull(),
    errorLevel: varchar("ErrorLevel", { length: 1 }).notNull(),
    nameCode: varchar("NameCode", { length: 1 }).notNull(),
    dateAdded: date("DateAdded").notNull(),
    blockEmail: varchar("BlockEMail", { length: 1 }).notNull(),
    blockMail: varchar("BlockMail", { length: 1 }).notNull(),
    blockPhone: varchar("BlockPhone", { length: 1 }).notNull(),
    mailability: varchar("Mailability", { length: 1 }),
    nameBalances1: numeric("NameBalances1", { precision: 15, scale: 2 }),
    address: varchar("Address", { length: 45 }),
    addressSecondLine: varchar("AddressSecondLine", { length: 45 }),
    businessPhone: varchar("BusinessPhone", { length: 20 }),
    businessPhoneExt: varchar("BusinessPhoneExt", { length: 7 }),
    cellular: varchar("Cellular", { length: 20 }),
    city: varchar("City", { length: 35 }),
    contactMethod: varchar("ContactMethod", { length: 1 }),
    country: varchar("Country", { length: 20 }),
    county: varchar("County", { length: 25 }),
    driverLicenseStOrProv: varchar("DriverLicenseStOrProv", { length: 2 }),
    email: varchar("Email", { length: 50 }),
    emailDesc: varchar("EmailDesc", { length: 20 }),
    emailDesc2: varchar("EmailDesc2", { length: 20 }),
    emailDesc3: varchar("EmailDesc3", { length: 20 }),
    employer: varchar("Employer", { length: 32 }),
    errorMessage: varchar("ErrorMessage", { length: 80 }),
    firstName: varchar("FirstName", { length: 25 }),
    homeFax: varchar("HomeFax", { length: 20 }),
    telephone: varchar("Telephone", { length: 12 }),
    language: varchar("Language", { length: 2 }),
    lastName: varchar("LastName", { length: 40 }),
    middleName: varchar("MiddleName", { length: 25 }),
    name1: varchar("Name1", { length: 45 }),
    name2Company: varchar("Name2Company", { length: 30 }),
    nameCompany: varchar("NameCompany", { length: 45 }),
    pager: varchar("Pager", { length: 20 }),
    partsCounterCode: varchar("PartsCounterCode", { length: 20 }),
    partsFlag: varchar("PartsFlag", { length: 2 }),
    partsType: varchar("PartsType", { length: 1 }),
    preferredContactDay: varchar("PreferredContactDay", { length: 1 }),
    preferredContactMethod: varchar("PreferredContactMethod", { length: 1 }),
    preferredContactTime: varchar("PreferredContactTime", { length: 1 }),
    saleType: varchar("SaleType", { length: 20 }),
    secondaryHomePhone: varchar("SecondaryHomePhone", { length: 12 }),
    state: varchar("State", { length: 2 }),
    taxCode: varchar("TaxCode", { length: 20 }),
    title1: varchar("Title1", { length: 30 }),
    zipOrPostalCode: varchar("ZipOrPostalCode", { length: 20 }),
    homePhone: varchar("HomePhone", { length: 12 }),
    preferredLanguage: varchar("PreferredLanguage", { length: 20 }),
    comment: varchar("Comment", { length: 255 }),
    commentDate: date("CommentDate"),
    driverLicenseExpDate: date("DriverLicenseExpDate"),
    email2: varchar("Email2", { length: 50 }),
    email3: varchar("Email3", { length: 50 }),
    lastUpdated: date("LastUpdated"),
    gender: varchar("Gender", { length: 1 }),
    creditLimit: numeric("CreditLimit", { precision: 15, scale: 2 }),
    currentDue: numeric("CurrentDue", { precision: 12, scale: 2 }),
    over30Due: numeric("Over30Due", { precision: 12, scale: 2 }),
    over60Due: numeric("Over60Due", { precision: 12, scale: 2 }),
    over90Due: numeric("Over90Due", { precision: 12, scale: 2 }),
    over120Due: numeric("Over120Due", { precision: 12, scale: 2 }),
    specInstructions2: varchar("SpecInstructions2", { length: 60 }),
    specInstructions3: varchar("SpecInstructions3", { length: 60 }),
    specInstructions4: varchar("SpecInstructions4", { length: 60 }),
    specInstructions5: varchar("SpecInstructions5", { length: 60 }),
    insAgency: varchar("InsAgency", { length: 30 }),
    insAgentAddress1: varchar("InsAgentAddress1", { length: 45 }),
    insAgentAddress2: varchar("InsAgentAddress2", { length: 45 }),
    insAgentCity: varchar("InsAgentCity", { length: 35 }),
    insAgentPhone: varchar("InsAgentPhone", { length: 20 }),
    insAgentState: varchar("InsAgentState", { length: 2 }),
    insAgentZipOrPostalCode: varchar("InsAgentZipOrPostalCode", { length: 20 }),
    insCompanyAddress1: varchar("InsCompanyAddress1", { length: 45 }),
    insCompanyAddress2: varchar("InsCompanyAddress2", { length: 45 }),
    insCompanyCity: varchar("InsCompanyCity", { length: 35 }),
    insCompanyPhone: varchar("InsCompanyPhone", { length: 20 }),
    insCompanyState: varchar("InsCompanyState", { length: 2 }),
    insCompanyZipOrPostalCode: varchar("InsCompanyZipOrPostalCode", {
      length: 20,
    }),
    insPolicyExpDate: date("InsPolicyExpDate"),
    insVerifiedBy: varchar("InsVerifiedBy", { length: 30 }),
    insVerifiedDate: date("InsVerifiedDate"),
    insPolicyNo: varchar("InsPolicyNo", { length: 25 }),
    serviceCustomer: varchar("ServiceCustomer", { length: 2 }),
    textMessagePhone: varchar("TextMessagePhone", { length: 20 }),
    textMessageCarrier: varchar("TextMessageCarrier", { length: 25 }),
    name2First: varchar("Name2First", { length: 20 }),
    name2Last: varchar("Name2Last", { length: 30 }),
    name2Middle: varchar("Name2Middle", { length: 20 }),
    name2Suffix: varchar("Name2Suffix", { length: 5 }),
    name2Title: varchar("Name2Title", { length: 5 }),
    nameSuffix: varchar("NameSuffix", { length: 5 }),
    nameTitle: varchar("NameTitle", { length: 5 }),
    insAgent: varchar("InsAgent", { length: 30 }),
    insCompany: varchar("InsCompany", { length: 30 }),
    specInstructions: varchar("SpecInstructions", { length: 40 }),
    deleteDataFlag: smallint("DeleteDataFlag"),
    optOutFlag: smallint("OptOutFlag"),
    optOutDate: date("OptOutDate"),
    optOutTime: varchar("OptOutTime", { length: 20 }),
    deleteDataDate: date("DeleteDataDate"),
    deleteDataTime: varchar("DeleteDataTime", { length: 20 }),
  },
  (table) => {
    return {
      customersPkey: primaryKey({
        columns: [table.hostItemId, table.custNo],
        name: "customers_pkey",
      }),
    };
  },
);

export const deals = pgTable(
  "deals",
  {
    FiWipStatusCode: varchar("FiWipStatusCode", { length: 2 }).notNull(),
    Branch: varchar("Branch", { length: 20 }).notNull(),
    HostItemID: varchar("HostItemID", { length: 20 }).notNull(),
    State: varchar("State", { length: 2 }),
    Make: varchar("Make", { length: 50 }),
    MakeName: varchar("MakeName", { length: 50 }),
    MileageExpected: integer("MileageExpected"),
    MileagePenaltyRate: numeric("MileagePenaltyRate", {
      precision: 10,
      scale: 2,
    }),
    StockNo: varchar("StockNo", { length: 50 }),
    Tax: numeric("Tax", { precision: 10, scale: 2 }),
    Tax1Name: varchar("Tax1Name", { length: 50 }),
    Tax1Rate: numeric("Tax1Rate", { precision: 10, scale: 2 }),
    Tax1Base: numeric("Tax1Base", { precision: 10, scale: 2 }),
    Tax1Amount: numeric("Tax1Amount", { precision: 10, scale: 2 }),
    MBITerm: smallint("MBITerm"),
    MSRP: numeric("MSRP", { precision: 10, scale: 2 }),
    MbiPolicyNo: varchar("MbiPolicyNo", { length: 50 }),
    MileagePenaltyAmount: varchar("MileagePenaltyAmount", { length: 50 }),
    SurplusCash: numeric("SurplusCash", { precision: 10, scale: 2 }),
    Tax2Amount: numeric("Tax2Amount", { precision: 10, scale: 2 }),
    Tax2Name: varchar("Tax2Name", { length: 50 }),
    Tax2Rate: numeric("Tax2Rate", { precision: 10, scale: 2 }),
    Tax3Amount: numeric("Tax3Amount", { precision: 10, scale: 2 }),
    Tax3Name: varchar("Tax3Name", { length: 50 }),
    Tax3Rate: numeric("Tax3Rate", { precision: 10, scale: 2 }),
    Tax4Amount: numeric("Tax4Amount", { precision: 10, scale: 2 }),
    Tax4Name: varchar("Tax4Name", { length: 50 }),
    Tax4Rate: numeric("Tax4Rate", { precision: 10, scale: 2 }),
    USLuxuryExciseTaxAmount: numeric("USLuxuryExciseTaxAmount", {
      precision: 10,
      scale: 2,
    }),
    FeeOption3Amount: numeric("FeeOption3Amount", { precision: 10, scale: 2 }),
    FeeOption3Cost: numeric("FeeOption3Cost", { precision: 10, scale: 2 }),
    FeeOption3Name: varchar("FeeOption3Name", { length: 25 }),
    FeeOption3ProfitType: varchar("FeeOption3ProfitType", { length: 2 }),
    FeeOption4Amount: numeric("FeeOption4Amount", { precision: 10, scale: 2 }),
    FeeOption4Cost: numeric("FeeOption4Cost", { precision: 10, scale: 2 }),
    FeeOption4Name: varchar("FeeOption4Name", { length: 25 }),
    FeeOption4ProfitType: varchar("FeeOption4ProfitType", { length: 2 }),
    FeeOption5Amount: numeric("FeeOption5Amount", { precision: 10, scale: 2 }),
    FeeOption5Cost: numeric("FeeOption5Cost", { precision: 10, scale: 2 }),
    FeeOption5Name: varchar("FeeOption5Name", { length: 25 }),
    FeeOption5ProfitType: varchar("FeeOption5ProfitType", { length: 2 }),
    FeeOption6Amount: numeric("FeeOption6Amount", { precision: 10, scale: 2 }),
    FeeOption6Cost: numeric("FeeOption6Cost", { precision: 10, scale: 2 }),
    FeeOption6Name: varchar("FeeOption6Name", { length: 25 }),
    FeeOption6ProfitType: varchar("FeeOption6ProfitType", { length: 2 }),
    FeeOption7Amount: numeric("FeeOption7Amount", { precision: 10, scale: 2 }),
    FeeOption7Cost: numeric("FeeOption7Cost", { precision: 10, scale: 2 }),
    FeeOption7Name: varchar("FeeOption7Name", { length: 25 }),
    FeeOption7ProfitType: varchar("FeeOption7ProfitType", { length: 2 }),
    FeeOption8Amount: numeric("FeeOption8Amount", { precision: 10, scale: 2 }),
    FeeOption8Cost: numeric("FeeOption8Cost", { precision: 10, scale: 2 }),
    FeeOption8Name: varchar("FeeOption8Name", { length: 25 }),
    FeeOption8ProfitType: varchar("FeeOption8ProfitType", { length: 2 }),
    FeeOption9Amount: numeric("FeeOption9Amount", { precision: 10, scale: 2 }),
    FeeOption9Cost: numeric("FeeOption9Cost", { precision: 10, scale: 2 }),
    FeeOption9Name: varchar("FeeOption9Name", { length: 18 }),
    FeeOption9ProfitType: varchar("FeeOption9ProfitType", { length: 2 }),
    InitialFee4ProfitType: varchar("InitialFee4ProfitType", { length: 1 }),
    InitialFee5Amount: numeric("InitialFee5Amount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee5CostAmount: numeric("InitialFee5CostAmount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee5Name: varchar("InitialFee5Name", { length: 21 }),
    InitialFee5ProfitType: varchar("InitialFee5ProfitType", { length: 1 }),
    InitialFee6Amount: numeric("InitialFee6Amount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee6CostAmount: numeric("InitialFee6CostAmount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee6Name: varchar("InitialFee6Name", { length: 21 }),
    InitialFee6ProfitType: varchar("InitialFee6ProfitType", { length: 1 }),
    InitialFee7Amount: numeric("InitialFee7Amount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee7CostAmount: numeric("InitialFee7CostAmount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee7Name: varchar("InitialFee7Name", { length: 21 }),
    InitialFee7ProfitType: varchar("InitialFee7ProfitType", { length: 1 }),
    InitialFee8Amount: numeric("InitialFee8Amount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee8CostAmount: numeric("InitialFee8CostAmount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee8Name: varchar("InitialFee8Name", { length: 21 }),
    InitialFee8ProfitType: varchar("InitialFee8ProfitType", { length: 1 }),
    InitialFee9Amount: numeric("InitialFee9Amount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee9CostAmount: numeric("InitialFee9CostAmount", {
      precision: 10,
      scale: 2,
    }),
    InitialFee9Name: varchar("InitialFee9Name", { length: 21 }),
    InitialFee9ProfitType: varchar("InitialFee9ProfitType", { length: 1 }),
    Ins1Cost: numeric("Ins1Cost", { precision: 10, scale: 2 }),
    Ins1Fee: numeric("Ins1Fee", { precision: 10, scale: 2 }),
    Ins1Income: numeric("Ins1Income", { precision: 10, scale: 2 }),
    Ins2Cost: numeric("Ins2Cost", { precision: 10, scale: 2 }),
    Ins2Fee: numeric("Ins2Fee", { precision: 10, scale: 2 }),
    Ins2Income: numeric("Ins2Income", { precision: 10, scale: 2 }),
    Ins3Cost: numeric("Ins3Cost", { precision: 10, scale: 2 }),
    Ins3Fee: numeric("Ins3Fee", { precision: 10, scale: 2 }),
    Ins3Income: numeric("Ins3Income", { precision: 10, scale: 2 }),
    Insurance1Deductible: numeric("Insurance1Deductible", {
      precision: 10,
      scale: 2,
    }),
    Insurance1Limit: numeric("Insurance1Limit", { precision: 10, scale: 2 }),
    Insurance1LimitMiles: smallint("Insurance1LimitMiles"),
    Insurance1Name: varchar("Insurance1Name", { length: 21 }),
    BalloonRate: numeric("BalloonRate", { precision: 10, scale: 2 }),
    OnePayAmount: numeric("OnePayAmount", { precision: 10, scale: 2 }),
    FinInstituteCode: varchar("FinInstituteCode", { length: 12 }),
    FinanceAmt: numeric("FinanceAmt", { precision: 10, scale: 2 }),
    FinanceCharge: numeric("FinanceCharge", { precision: 10, scale: 2 }),
    FinanceSource: varchar("FinanceSource", { length: 50 }),
    FirstPayDate: date("FirstPayDate"),
    BackGross: numeric("BackGross", { precision: 10, scale: 2 }),
    BackWeOwes: numeric("BackWeOwes", { precision: 10, scale: 2 }),
    BalloonAmount: numeric("BalloonAmount", { precision: 10, scale: 2 }),
    BankFee: numeric("BankFee", { precision: 10, scale: 2 }),
    BaseResidual: numeric("BaseResidual", { precision: 10, scale: 2 }),
    BillingClerk: integer("BillingClerk"),
    BodyStyle: varchar("BodyStyle", { length: 50 }),
    BonusSP1: numeric("BonusSP1", { precision: 10, scale: 2 }),
    BonusSP2: numeric("BonusSP2", { precision: 10, scale: 2 }),
    BonusSP3: numeric("BonusSP3", { precision: 10, scale: 2 }),
    BusinessPhone: varchar("BusinessPhone", { length: 50 }),
    BuyRateAPR: numeric("BuyRateAPR", { precision: 10, scale: 2 }),
    BuyRateAddOn: numeric("BuyRateAddOn", { precision: 10, scale: 2 }),
    BuyRateLFM: numeric("BuyRateLFM", { precision: 10, scale: 2 }),
    BuyRateLMF: numeric("BuyRateLMF", { precision: 10, scale: 2 }),
    CLCost: numeric("CLCost", { precision: 10, scale: 2 }),
    CLIncome: numeric("CLIncome", { precision: 10, scale: 2 }),
    CLPremium: numeric("CLPremium", { precision: 10, scale: 2 }),
    CRMClosingMgrId: varchar("CRMClosingMgrId", { length: 50 }),
    CRMClosingMgrName: varchar("CRMClosingMgrName", { length: 50 }),
    CRMCommisionClosingMgr: varchar("CRMCommisionClosingMgr", { length: 50 }),
    CRMCommisionFIMgr: numeric("CRMCommisionFIMgr", {
      precision: 10,
      scale: 2,
    }),
    CRMCommisionSP1: numeric("CRMCommisionSP1", { precision: 10, scale: 2 }),
    CRMCommisionSP2: numeric("CRMCommisionSP2", { precision: 10, scale: 2 }),
    CRMCommisionSP3: numeric("CRMCommisionSP3", { precision: 10, scale: 2 }),
    CRMCommisionSalesMgr: numeric("CRMCommisionSalesMgr", {
      precision: 10,
      scale: 2,
    }),
    CRMCommisionTotal: numeric("CRMCommisionTotal", {
      precision: 10,
      scale: 2,
    }),
    CRMFIMgrId: varchar("CRMFIMgrId", { length: 50 }),
    CRMFIMgrName: varchar("CRMFIMgrName", { length: 50 }),
    CRMFlag: smallint("CRMFlag"),
    VIN: varchar("VIN", { length: 17 }),
    VehInventoryCompany: smallint("VehInventoryCompany"),
    VehSaleCompany: smallint("VehSaleCompany"),
    VehicleMileage: integer("VehicleMileage"),
    WAQNumber: integer("WAQNumber"),
    WarrantyFee: numeric("WarrantyFee", { precision: 10, scale: 2 }),
    WeOweBackSaleTotal: numeric("WeOweBackSaleTotal", {
      precision: 10,
      scale: 2,
    }),
    WeOweCostTotal: numeric("WeOweCostTotal", { precision: 10, scale: 2 }),
    WeOweFrontGrossSales: numeric("WeOweFrontGrossSales", {
      precision: 10,
      scale: 2,
    }),
    WeOweResidualTableTotal: numeric("WeOweResidualTableTotal", {
      precision: 10,
      scale: 2,
    }),
    WeOweResidualTotal: numeric("WeOweResidualTotal", {
      precision: 10,
      scale: 2,
    }),
    WeOweSaleHardTotal: numeric("WeOweSaleHardTotal", {
      precision: 10,
      scale: 2,
    }),
    WeOweSaleSoftTotal: numeric("WeOweSaleSoftTotal", {
      precision: 10,
      scale: 2,
    }),
    WeOweSaleTotal: numeric("WeOweSaleTotal", { precision: 10, scale: 2 }),
    Year: integer("Year"),
    ZipOrPostalCode: varchar("ZipOrPostalCode", { length: 20 }),
    SecurityDepositAmount: numeric("SecurityDepositAmount", {
      precision: 10,
      scale: 2,
    }),
    SellRateAPR: numeric("SellRateAPR", { precision: 10, scale: 2 }),
    SellRateAddOn: numeric("SellRateAddOn", { precision: 10, scale: 2 }),
    SellRateLMF: numeric("SellRateLMF", { precision: 10, scale: 2 }),
    ServiceTaxAmount: numeric("ServiceTaxAmount", { precision: 10, scale: 2 }),
    LeaseEndPercentageRate: smallint("LeaseEndPercentageRate"),
    LeaseEndValue: numeric("LeaseEndValue", { precision: 10, scale: 2 }),
    LeaseMileageAllowance: integer("LeaseMileageAllowance"),
    LeasePayment: numeric("LeasePayment", { precision: 10, scale: 2 }),
    LeaseType: varchar("LeaseType", { length: 2 }),
    LevelizedLifeAmount: numeric("LevelizedLifeAmount", {
      precision: 10,
      scale: 2,
    }),
    LevelizedLifeDealerComm: numeric("LevelizedLifeDealerComm", {
      precision: 10,
      scale: 2,
    }),
    LevelizedLifeIncome: numeric("LevelizedLifeIncome", {
      precision: 10,
      scale: 2,
    }),
    LienHolderAddress: varchar("LienHolderAddress", { length: 100 }),
    LienHolderCity: varchar("LienHolderCity", { length: 50 }),
    LienHolderName: varchar("LienHolderName", { length: 100 }),
    LienHolderName2: varchar("LienHolderName2", { length: 100 }),
    LienHolderPhone: varchar("LienHolderPhone", { length: 20 }),
    LienHolderState: varchar("LienHolderState", { length: 2 }),
    LienHolderZip: varchar("LienHolderZip", { length: 20 }),
    AddToCapCostFee4ProfitType: varchar("AddToCapCostFee4ProfitType", {
      length: 2,
    }),
    AddToCapCostFee5Amount: numeric("AddToCapCostFee5Amount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee5CostAmount: numeric("AddToCapCostFee5CostAmount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee5Name: varchar("AddToCapCostFee5Name", { length: 25 }),
    AddToCapCostFee5ProfitType: varchar("AddToCapCostFee5ProfitType", {
      length: 2,
    }),
    AddToCapCostFee6Amount: numeric("AddToCapCostFee6Amount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee6CostAmount: numeric("AddToCapCostFee6CostAmount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee6Name: varchar("AddToCapCostFee6Name", { length: 25 }),
    AddToCapCostFee6ProfitType: varchar("AddToCapCostFee6ProfitType", {
      length: 2,
    }),
    AddToCapCostFee7Amount: numeric("AddToCapCostFee7Amount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee7CostAmount: numeric("AddToCapCostFee7CostAmount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee7Name: varchar("AddToCapCostFee7Name", { length: 25 }),
    AddToCapCostFee7ProfitType: varchar("AddToCapCostFee7ProfitType", {
      length: 2,
    }),
    Address: varchar("Address", { length: 100 }),
    AdjustedCapCost: numeric("AdjustedCapCost", { precision: 10, scale: 2 }),
    AdjustedCostofVehicle: numeric("AdjustedCostofVehicle", {
      precision: 10,
      scale: 2,
    }),
    AdjustmentsDealerDefined: numeric("AdjustmentsDealerDefined", {
      precision: 10,
      scale: 2,
    }),
    AdjustmentsROPO: numeric("AdjustmentsROPO", { precision: 10, scale: 2 }),
    AdjustmentsStandard: numeric("AdjustmentsStandard", {
      precision: 10,
      scale: 2,
    }),
    Age: smallint("Age"),
    AmountDueAtStart: numeric("AmountDueAtStart", { precision: 10, scale: 2 }),
    AnnualFee1Amount: numeric("AnnualFee1Amount", { precision: 10, scale: 2 }),
    AnnualFee1Name: varchar("AnnualFee1Name", { length: 25 }),
    AnnualFee2Amount: numeric("AnnualFee2Amount", { precision: 10, scale: 2 }),
    AnnualFee2Name: varchar("AnnualFee2Name", { length: 25 }),
    AnnualFee3Amount: numeric("AnnualFee3Amount", { precision: 10, scale: 2 }),
    AnnualFee3Name: varchar("AnnualFee3Name", { length: 25 }),
    AnnualFee3DealerCommBase: numeric("AnnualFee3DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    AnnualFee4Amount: numeric("AnnualFee4Amount", { precision: 10, scale: 2 }),
    AnnualFee4Name: varchar("AnnualFee4Name", { length: 25 }),
    AnnualFee4DealerCommBase: numeric("AnnualFee4DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    AnnualFee5Amount: numeric("AnnualFee5Amount", { precision: 10, scale: 2 }),
    AnnualFee5Name: varchar("AnnualFee5Name", { length: 25 }),
    AnnualFee5DealerCommBase: numeric("AnnualFee5DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    AssnSlsperson: varchar("AssnSlsperson", { length: 50 }),
    Insurance1Term: integer("Insurance1Term"),
    Insurance2Deductible: numeric("Insurance2Deductible", {
      precision: 10,
      scale: 2,
    }),
    Insurance2Limit: numeric("Insurance2Limit", { precision: 10, scale: 2 }),
    Insurance2LimitMiles: integer("Insurance2LimitMiles"),
    Insurance2Name: varchar("Insurance2Name", { length: 50 }),
    Insurance2Term: integer("Insurance2Term"),
    Insurance3Deductible: numeric("Insurance3Deductible", {
      precision: 10,
      scale: 2,
    }),
    Insurance3Limit: numeric("Insurance3Limit", { precision: 10, scale: 2 }),
    Insurance3LimitMiles: integer("Insurance3LimitMiles"),
    Insurance3Name: varchar("Insurance3Name", { length: 50 }),
    Insurance3Term: integer("Insurance3Term"),
    InsuranceCommDlr: numeric("InsuranceCommDlr", { precision: 10, scale: 2 }),
    InsuranceTypeCode: varchar("InsuranceTypeCode", { length: 50 }),
    LSTGSTAmount: numeric("LSTGSTAmount", { precision: 10, scale: 2 }),
    LSTGSTRate: numeric("LSTGSTRate", { precision: 5, scale: 4 }),
    LSTGSTRateFlat: numeric("LSTGSTRateFlat", { precision: 10, scale: 2 }),
    LastPayAmount: numeric("LastPayAmount", { precision: 10, scale: 2 }),
    LastPayDate: date("LastPayDate"),
    OutTheDoorPrice: numeric("OutTheDoorPrice", { precision: 10, scale: 2 }),
    PaymentAmt: numeric("PaymentAmt", { precision: 10, scale: 2 }),
    PaymentCode: varchar("PaymentCode", { length: 50 }),
    PaymentStyle: varchar("PaymentStyle", { length: 50 }),
    Payments: integer("Payments"),
    PickupDate1: date("PickupDate1"),
    PickupDate2: date("PickupDate2"),
    PickupDate3: date("PickupDate3"),
    PickupPay1: numeric("PickupPay1", { precision: 10, scale: 2 }),
    PickupPay2: numeric("PickupPay2", { precision: 10, scale: 2 }),
    PickupPay3: numeric("PickupPay3", { precision: 10, scale: 2 }),
    ExtWarrantyExpMilesLease: integer("ExtWarrantyExpMilesLease"),
    ExtWarrantyTermLease: integer("ExtWarrantyTermLease"),
    FIDealType: varchar("FIDealType", { length: 5 }),
    FIIncome: numeric("FIIncome", { precision: 10, scale: 2 }),
    FIMgr1: varchar("FIMgr1", { length: 50 }),
    FIMgr2: varchar("FIMgr2", { length: 50 }),
    FeeOption10Amount: numeric("FeeOption10Amount", {
      precision: 10,
      scale: 2,
    }),
    FeeOption10Cost: numeric("FeeOption10Cost", { precision: 10, scale: 2 }),
    FeeOption10Name: varchar("FeeOption10Name", { length: 50 }),
    FeeOption10ProfitType: varchar("FeeOption10ProfitType", { length: 5 }),
    FeeOption1Amount: numeric("FeeOption1Amount", { precision: 10, scale: 2 }),
    FeeOption1Cost: numeric("FeeOption1Cost", { precision: 10, scale: 2 }),
    FeeOption1Name: varchar("FeeOption1Name", { length: 50 }),
    FeeOption1ProfitType: varchar("FeeOption1ProfitType", { length: 5 }),
    FeeOption2Amount: numeric("FeeOption2Amount", { precision: 10, scale: 2 }),
    FeeOption2Cost: numeric("FeeOption2Cost", { precision: 10, scale: 2 }),
    FeeOption2Name: varchar("FeeOption2Name", { length: 50 }),
    FeeOption2ProfitType: varchar("FeeOption2ProfitType", { length: 5 }),
    RebateAmount: numeric("RebateAmount", { precision: 10, scale: 2 }),
    SLSDealType: varchar("SLSDealType", { length: 50 }),
    SaleCreditSP1: numeric("SaleCreditSP1", { precision: 10, scale: 2 }),
    SaleCreditSP2: numeric("SaleCreditSP2", { precision: 10, scale: 2 }),
    SaleCreditSP3: numeric("SaleCreditSP3", { precision: 10, scale: 2 }),
    SalePriceWithWeOwes: numeric("SalePriceWithWeOwes", {
      precision: 10,
      scale: 2,
    }),
    SaleType: varchar("SaleType", { length: 50 }),
    SalesAccount: varchar("SalesAccount", { length: 50 }),
    SalesDate: date("SalesDate"),
    SalesManagementDealType: varchar("SalesManagementDealType", { length: 50 }),
    SalesMgr: varchar("SalesMgr", { length: 50 }),
    Salesperson1: varchar("Salesperson1", { length: 50 }),
    Salesperson2: varchar("Salesperson2", { length: 50 }),
    Salesperson3: varchar("Salesperson3", { length: 50 }),
    CRMSP1Id: varchar("CRMSP1Id", { length: 50 }),
    CRMSP1Name: varchar("CRMSP1Name", { length: 50 }),
    CRMSP2Id: varchar("CRMSP2Id", { length: 50 }),
    CRMSP2Name: varchar("CRMSP2Name", { length: 50 }),
    CRMSP3Id: varchar("CRMSP3Id", { length: 50 }),
    CRMSP3Name: varchar("CRMSP3Name", { length: 50 }),
    CRMSaleCreditClosingMgr: numeric("CRMSaleCreditClosingMgr", {
      precision: 10,
      scale: 2,
    }),
    CRMSaleCreditFIMgr: numeric("CRMSaleCreditFIMgr", {
      precision: 10,
      scale: 2,
    }),
    CRMSaleCreditSP1: numeric("CRMSaleCreditSP1", { precision: 10, scale: 2 }),
    CRMSaleCreditSP2: numeric("CRMSaleCreditSP2", { precision: 10, scale: 2 }),
    CRMSaleCreditSP3: numeric("CRMSaleCreditSP3", { precision: 10, scale: 2 }),
    CRMSaleCreditSalesMgr: numeric("CRMSaleCreditSalesMgr", {
      precision: 10,
      scale: 2,
    }),
    CRMSaleType: varchar("CRMSaleType", { length: 50 }),
    CRMSalesCreditTotal: numeric("CRMSalesCreditTotal", {
      precision: 10,
      scale: 2,
    }),
    CRMSalesMgrId: varchar("CRMSalesMgrId", { length: 50 }),
    CRMSalesMgrName: varchar("CRMSalesMgrName", { length: 50 }),
    CRMSpiffClosingMgr: numeric("CRMSpiffClosingMgr", {
      precision: 10,
      scale: 2,
    }),
    CRMSpiffFIMgr: numeric("CRMSpiffFIMgr", { precision: 10, scale: 2 }),
    CRMSpiffSP1: numeric("CRMSpiffSP1", { precision: 10, scale: 2 }),
    CRMSpiffSP2: numeric("CRMSpiffSP2", { precision: 10, scale: 2 }),
    CRMSpiffSP3: numeric("CRMSpiffSP3", { precision: 10, scale: 2 }),
    CRMSpiffSalesMgr: numeric("CRMSpiffSalesMgr", { precision: 10, scale: 2 }),
    CRMSpiffTotal: numeric("CRMSpiffTotal", { precision: 10, scale: 2 }),
    CalcMethod: varchar("CalcMethod", { length: 50 }),
    CashCapReduction: numeric("CashCapReduction", { precision: 10, scale: 2 }),
    CashDown: numeric("CashDown", { precision: 10, scale: 2 }),
    CashPrice: numeric("CashPrice", { precision: 10, scale: 2 }),
    City: varchar("City", { length: 50 }),
    ClosingMgr: varchar("ClosingMgr", { length: 50 }),
    CoAddress: varchar("CoAddress", { length: 100 }),
    CoBusinessPhone: varchar("CoBusinessPhone", { length: 20 }),
    CoBuyer: varchar("CoBuyer", { length: 50 }),
    CoCity: varchar("CoCity", { length: 50 }),
    CoCounty: varchar("CoCounty", { length: 50 }),
    CoCustNo: varchar("CoCustNo", { length: 50 }),
    CoHomePhone: varchar("CoHomePhone", { length: 20 }),
    CoName1: varchar("CoName1", { length: 50 }),
    CoState: varchar("CoState", { length: 2 }),
    CoZipOrPostalCode: varchar("CoZipOrPostalCode", { length: 20 }),
    DealerDefined6: varchar("DealerDefined6", { length: 50 }),
    DealerDefined7: varchar("DealerDefined7", { length: 50 }),
    DealerDefined8: varchar("DealerDefined8", { length: 50 }),
    DeliveryCoord: varchar("DeliveryCoord", { length: 50 }),
    DepositAmount: numeric("DepositAmount", { precision: 10, scale: 2 }),
    DepositType: varchar("DepositType", { length: 50 }),
    DueOnDelivery: numeric("DueOnDelivery", { precision: 10, scale: 2 }),
    FrontEndGrossProfit: numeric("FrontEndGrossProfit", {
      precision: 10,
      scale: 2,
    }),
    FrontGross: numeric("FrontGross", { precision: 10, scale: 2 }),
    FrontWeOwes: numeric("FrontWeOwes", { precision: 10, scale: 2 }),
    FrontWeOwesGrossCost: numeric("FrontWeOwesGrossCost", {
      precision: 10,
      scale: 2,
    }),
    FrontWeOwesGrossSales: numeric("FrontWeOwesGrossSales", {
      precision: 10,
      scale: 2,
    }),
    GLVehicleCost: numeric("GLVehicleCost", { precision: 10, scale: 2 }),
    GrossProfit: numeric("GrossProfit", { precision: 10, scale: 2 }),
    HomePhone: varchar("HomePhone", { length: 20 }),
    IncentiveDealer: numeric("IncentiveDealer", { precision: 10, scale: 2 }),
    IncentiveProgram: varchar("IncentiveProgram", { length: 50 }),
    MBICarrier: varchar("MBICarrier", { length: 50 }),
    MBICost: numeric("MBICost", { precision: 10, scale: 2 }),
    MBIDeductible: numeric("MBIDeductible", { precision: 10, scale: 2 }),
    MBIEligComment: varchar("MBIEligComment", { length: 200 }),
    MBIEligFlag: varchar("MBIEligFlag", { length: 5 }),
    MBIFee: numeric("MBIFee", { precision: 10, scale: 2 }),
    MBIIncome: numeric("MBIIncome", { precision: 10, scale: 2 }),
    MBILimit: numeric("MBILimit", { precision: 10, scale: 2 }),
    MBILimitMax: numeric("MBILimitMax", { precision: 10, scale: 2 }),
    MBIName: varchar("MBIName", { length: 50 }),
    AHCost: numeric("AHCost", { precision: 10, scale: 2 }),
    AHIncome: numeric("AHIncome", { precision: 10, scale: 2 }),
    AHPremium: numeric("AHPremium", { precision: 10, scale: 2 }),
    APR: numeric("APR", { precision: 5, scale: 2 }),
    AccountingAccount: varchar("AccountingAccount", { length: 50 }),
    AccountingDate: date("AccountingDate"),
    AddCapCostFee3DealerCommBase: numeric("AddCapCostFee3DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    AddCapCostFee4DealerCommBase: numeric("AddCapCostFee4DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    AddCapCostFee5DealerCommBase: numeric("AddCapCostFee5DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    AddCapCostFee6DealerCommBase: numeric("AddCapCostFee6DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    AddCapCostFee7DealerCommBase: numeric("AddCapCostFee7DealerCommBase", {
      precision: 10,
      scale: 2,
    }),
    AddToCapAmount: numeric("AddToCapAmount", { precision: 10, scale: 2 }),
    AddToCapCostFee1Amount: numeric("AddToCapCostFee1Amount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee1CostAmount: numeric("AddToCapCostFee1CostAmount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee1Name: varchar("AddToCapCostFee1Name", { length: 50 }),
    AddToCapCostFee1ProfitType: varchar("AddToCapCostFee1ProfitType", {
      length: 5,
    }),
    AddToCapCostFee2Amount: numeric("AddToCapCostFee2Amount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee2CostAmount: numeric("AddToCapCostFee2CostAmount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee2Name: varchar("AddToCapCostFee2Name", { length: 50 }),
    AddToCapCostFee2ProfitType: varchar("AddToCapCostFee2ProfitType", {
      length: 5,
    }),
    AddToCapCostFee3Amount: numeric("AddToCapCostFee3Amount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee3CostAmount: numeric("AddToCapCostFee3CostAmount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee3Name: varchar("AddToCapCostFee3Name", { length: 50 }),
    AddToCapCostFee3ProfitType: varchar("AddToCapCostFee3ProfitType", {
      length: 5,
    }),
    AddToCapCostFee4Amount: numeric("AddToCapCostFee4Amount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee4CostAmount: numeric("AddToCapCostFee4CostAmount", {
      precision: 10,
      scale: 2,
    }),
    AddToCapCostFee4Flag: varchar("AddToCapCostFee4Flag", { length: 5 }),
    AddToCapCostFee4Name: varchar("AddToCapCostFee4Name", { length: 50 }),
    Email1: varchar("Email1", { length: 100 }),
    Email1Desc: varchar("Email1Desc", { length: 100 }),
    Email2: varchar("Email2", { length: 100 }),
    Email2Desc: varchar("Email2Desc", { length: 100 }),
    Email3: varchar("Email3", { length: 100 }),
    Email3Desc: varchar("Email3Desc", { length: 100 }),
    ErrorLevel: integer("ErrorLevel"),
    ErrorMessage: varchar("ErrorMessage", { length: 255 }),
    Miscellaneous1: varchar("Miscellaneous1", { length: 50 }),
    Miscellaneous2: varchar("Miscellaneous2", { length: 50 }),
    Model: varchar("Model", { length: 50 }),
    ModelName: text("ModelName"),
    ModelNo: varchar("ModelNo", { length: 50 }),
    ModelType: varchar("ModelType", { length: 50 }),
    Name: varchar("Name", { length: 50 }),
    Name1: varchar("Name1", { length: 50 }),
    NetTrade1: numeric("NetTrade1", { precision: 12, scale: 2 }),
    NetTrade2: numeric("NetTrade2", { precision: 12, scale: 2 }),
    OptionsCommDlr: numeric("OptionsCommDlr", { precision: 12, scale: 2 }),
    Term: integer("Term"),
    TexasGAPInsuranceAmount: numeric("TexasGAPInsuranceAmount", {
      precision: 12,
      scale: 2,
    }),
    TexasGAPInsuranceDealerCommissionBase: numeric(
      "TexasGAPInsuranceDealerCommissionBase",
      { precision: 12, scale: 2 },
    ),
    TotalAnnFees: numeric("TotalAnnFees", { precision: 12, scale: 2 }),
    TotalCapReduction: numeric("TotalCapReduction", {
      precision: 12,
      scale: 2,
    }),
    TotalCashSurplus: numeric("TotalCashSurplus", { precision: 12, scale: 2 }),
    TotalCommission: numeric("TotalCommission", { precision: 12, scale: 2 }),
    TotalCommissionSP1: numeric("TotalCommissionSP1", {
      precision: 12,
      scale: 2,
    }),
    TotalCommissionSP2: numeric("TotalCommissionSP2", {
      precision: 12,
      scale: 2,
    }),
    TotalDown: numeric("TotalDown", { precision: 12, scale: 2 }),
    TotalFinancedFeeOptions: numeric("TotalFinancedFeeOptions", {
      precision: 12,
      scale: 2,
    }),
    TotalGross: numeric("TotalGross", { precision: 12, scale: 2 }),
    TotalInitFees: numeric("TotalInitFees", { precision: 12, scale: 2 }),
    TotalInsurancePremiums: numeric("TotalInsurancePremiums", {
      precision: 12,
      scale: 2,
    }),
    TotalOfMonthlyPayments: numeric("TotalOfMonthlyPayments", {
      precision: 12,
      scale: 2,
    }),
    TotalOptionsFees: numeric("TotalOptionsFees", { precision: 12, scale: 2 }),
    TotalTaxableFees: numeric("TotalTaxableFees", { precision: 12, scale: 2 }),
    TotalTradeAllowance: numeric("TotalTradeAllowance", {
      precision: 12,
      scale: 2,
    }),
    TotalTradesACV: numeric("TotalTradesACV", { precision: 12, scale: 2 }),
    TotalTradesNet: numeric("TotalTradesNet", { precision: 12, scale: 2 }),
    TotalTradesOver: numeric("TotalTradesOver", { precision: 12, scale: 2 }),
    TotalTradesPayoff: numeric("TotalTradesPayoff", {
      precision: 12,
      scale: 2,
    }),
    PurchaseFlexibleTax1Amount: numeric("PurchaseFlexibleTax1Amount", {
      precision: 12,
      scale: 2,
    }),
    PurchaseFlexibleTax1Base: numeric("PurchaseFlexibleTax1Base", {
      precision: 12,
      scale: 2,
    }),
    PurchaseFlexibleTax1Max: numeric("PurchaseFlexibleTax1Max", {
      precision: 12,
      scale: 2,
    }),
    PurchaseFlexibleTax1MaxCode: varchar("PurchaseFlexibleTax1MaxCode", {
      length: 50,
    }),
    PurchaseFlexibleTax1Name: varchar("PurchaseFlexibleTax1Name", {
      length: 50,
    }),
    PurchaseFlexibleTax1Rate: numeric("PurchaseFlexibleTax1Rate", {
      precision: 5,
      scale: 4,
    }),
    PurchaseFlexibleTax2Amount: numeric("PurchaseFlexibleTax2Amount", {
      precision: 12,
      scale: 2,
    }),
    PurchaseFlexibleTax2Base: numeric("PurchaseFlexibleTax2Base", {
      precision: 12,
      scale: 2,
    }),
    PurchaseFlexibleTax2Max: numeric("PurchaseFlexibleTax2Max", {
      precision: 12,
      scale: 2,
    }),
    PurchaseFlexibleTax2MaxCode: varchar("PurchaseFlexibleTax2MaxCode", {
      length: 50,
    }),
    PurchaseFlexibleTax2Name: varchar("PurchaseFlexibleTax2Name", {
      length: 50,
    }),
    PurchaseFlexibleTax2Rate: numeric("PurchaseFlexibleTax2Rate", {
      precision: 5,
      scale: 4,
    }),
    PurchaseMBICost: numeric("PurchaseMBICost", { precision: 12, scale: 2 }),
    PurchaseMBISP2CommAmount: numeric("PurchaseMBISP2CommAmount", {
      precision: 12,
      scale: 2,
    }),
    Color: varchar("Color", { length: 50 }),
    CommOnSaleDlr: numeric("CommOnSaleDlr", { precision: 12, scale: 2 }),
    CommissionPack: numeric("CommissionPack", { precision: 12, scale: 2 }),
    CommissionSP1: numeric("CommissionSP1", { precision: 12, scale: 2 }),
    CommissionSP2: numeric("CommissionSP2", { precision: 12, scale: 2 }),
    CommissionSP3: numeric("CommissionSP3", { precision: 12, scale: 2 }),
    Cont1Date: date("Cont1Date"),
    Cont1Reason: varchar("Cont1Reason", { length: 50 }),
    Cont2Date: date("Cont2Date"),
    Cont2Reason: varchar("Cont2Reason", { length: 50 }),
    ContractDate: date("ContractDate"),
    CostPrice: numeric("CostPrice", { precision: 12, scale: 2 }),
    County: varchar("County", { length: 50 }),
    CustNo: varchar("CustNo", { length: 20 }),
    CustOrCompanyCode: varchar("CustOrCompanyCode", { length: 50 }),
    CustomerCashDown: numeric("CustomerCashDown", { precision: 12, scale: 2 }),
    CustomerComments: text("CustomerComments"),
    InitFee10DealerCommissionBase: numeric("InitFee10DealerCommissionBase", {
      precision: 12,
      scale: 2,
    }),
    Timestamp: timestamp("Timestamp").notNull().defaultNow(),
  },
  (table) => {
    return {
      dealsPkey: primaryKey({
        columns: [table.FiWipStatusCode, table.Branch, table.HostItemID],
        name: "deals_pkey",
      }),
    };
  },
);

export const vehicles = pgTable("vehicles", {
  VIN: varchar("VIN", { length: 17 }).primaryKey(), // VINs are typically 17 characters long
  PrimaryDriverNo: text("PrimaryDriverNo"),
  AccountingAccount: text("AccountingAccount"),
  Model: text("Model"),
  ModelName: text("ModelName"),
  ModelType: text("ModelType"),
  TrimLevel: text("TrimLevel"),
  EngineDescription: text("EngineDescription"),
  EngineNo: text("EngineNo"),
  Color: text("Color"),
  InteriorColor: text("InteriorColor"),
  BodyStyle: text("BodyStyle"),
  FuelType: text("FuelType"),
  Year: integer("Year"),
  Make: text("Make"),
  MakeName: text("MakeName"),
  Manufacturer: text("Manufacturer"),
  PlantOfManufacture: text("PlantOfManufacture"),
  NumberOfDoors: integer("NumberOfDoors"),
  CylinderNo: integer("CylinderNo"),
  CommissionPrice: numeric("CommissionPrice", { precision: 10, scale: 2 }),
  RetailPriceUpdateDate: date("RetailPriceUpdateDate"),
  VehicleSoldDate: date("VehicleSoldDate"),
  SoldDate: date("SoldDate"),
  Mileage: integer("Mileage"),
  SoldMileage: integer("SoldMileage"),
  StockNo: text("StockNo"),
  StockType: text("StockType"),
  Status: text("Status"),
  Balance: numeric("Balance", { precision: 10, scale: 2 }),
  Price1: numeric("Price1", { precision: 10, scale: 2 }),
  Price2: numeric("Price2", { precision: 10, scale: 2 }),
  Options: text("Options"),
  OrderDate: date("OrderDate"),
  ExpectedDeliveryDate: date("ExpectedDeliveryDate"),
  ActualCashValue: numeric("ActualCashValue", { precision: 10, scale: 2 }),
  AdvertisedPrice: numeric("AdvertisedPrice", { precision: 10, scale: 2 }),
  AdvertisedPriceExpDate: date("AdvertisedPriceExpDate"),
  AdvertisedPriceStartDate: date("AdvertisedPriceStartDate"),
  TotalOptionsCost: numeric("TotalOptionsCost", { precision: 10, scale: 2 }),
  TotalOptionsInvoice: numeric("TotalOptionsInvoice", {
    precision: 10,
    scale: 2,
  }),
  TotalOptionsRetail: numeric("TotalOptionsRetail", {
    precision: 10,
    scale: 2,
  }),
  InvoicePackAmount: numeric("InvoicePackAmount", {
    precision: 10,
    scale: 2,
  }),
  CommissionPackAmount: numeric("CommissionPackAmount", {
    precision: 10,
    scale: 2,
  }),
  CommissionPackPercent: numeric("CommissionPackPercent", {
    precision: 10,
    scale: 2,
  }),
  EntryDate: date("EntryDate"),
  LastActivityDate: date("LastActivityDate"),
  AxleNo: text("AxleNo"),
  BaseInvoicePrice: numeric("BaseInvoicePrice", { precision: 10, scale: 2 }),
  CabType: text("CabType"),
  Chassis: text("Chassis"),
  DealerDefined1: text("DealerDefined1"),
  DealerDefined3: text("DealerDefined3"),
  DealerDefined5: text("DealerDefined5"),
  DealerDefined7: text("DealerDefined7"),
  DraftAmount: numeric("DraftAmount", { precision: 10, scale: 2 }),
  ErrorLevel: text("ErrorLevel"),
  FleetNo: text("FleetNo"),
  FreightOut: numeric("FreightOut", { precision: 10, scale: 2 }),
  FrontTire: text("FrontTire"),
  FullDescription: text("FullDescription"),
  HoldBackAmount: numeric("HoldBackAmount", { precision: 10, scale: 2 }),
  InventoryCompany: text("InventoryCompany"),
  InventorySourceName: text("InventorySourceName"),
  KeyNo: text("KeyNo"),
  LicenseExpirationDate: date("LicenseExpirationDate"),
  LotLocation: text("LotLocation"),
  ProductionNo: text("ProductionNo"),
  RearTire: text("RearTire"),
  RestraintSys: text("RestraintSys"),
  SaleCompany: text("SaleCompany"),
  StdEquip1: text("StdEquip1"),
  VehicleLicenseFee: numeric("VehicleLicenseFee", { precision: 10, scale: 2 }),
  VehicleStyle: text("VehicleStyle"),
  Wholesale: text("Wholesale"),
});
